provider: mongodbatlas
major-version: 3
esc:
    enabled: true
env:
    MONGODB_ATLAS_ORG_ID: ${{ secrets.MONGODB_ATLAS_ORG_ID }}
    MONGODB_ATLAS_PRIVATE_KEY: ${{ secrets.MONGODB_ATLAS_PRIVATE_KEY }}
    MONGODB_ATLAS_PUBLIC_KEY: ${{ secrets.MONGODB_ATLAS_PUBLIC_KEY }}
makeTemplate: bridged
team: ecosystem
license:
    ignore:
        - github.com/mongodb/terraform-provider-mongodbatlas/shim
pulumiConvert: 1
registryDocs: true
