provider: mongodbatlas
major-version: 3
env:
  MONGODB_ATLAS_ORG_ID: ${{ secrets.MONGODB_ATLAS_ORG_ID }}
  MONGODB_ATLAS_PRIVATE_KEY: ${{ secrets.MONGODB_ATLAS_PRIVATE_KEY }}
  MONGODB_ATLAS_PUBLIC_KEY: ${{ secrets.MONGODB_ATLAS_PUBLIC_KEY }}
makeTemplate: bridged
plugins:
  - name: aws 
    version: "4.0.0"
  - name: azure 
    version: "4.0.0"
  - name: gcp 
    version: "5.0.0"
team: ecosystem
javaGenVersion: "v0.9.5"
