provider: mongodbatlas
major-version: 3
env:
  MONGODB_ATLAS_ORG_ID: ${{ secrets.MONGODB_ATLAS_ORG_ID }}
  MONGODB_ATLAS_PRIVATE_KEY: ${{ secrets.MONGODB_ATLAS_PRIVATE_KEY }}
  MONGODB_ATLAS_PUBLIC_KEY: ${{ secrets.MONGODB_ATLAS_PUBLIC_KEY }}
makeTemplate: bridged
plugins:
  - name: terraform
    version: "1.0.16"
    kind: converter

  - name: aws
    version: "4.0.0"
  - name: azure
    version: "4.0.0"
  - name: gcp
    version: "5.0.0"
team: ecosystem
license:
  ignore:
    - github.com/mongodb/terraform-provider-mongodbatlas/shim
pulumiConvert: 1
registryDocs: true
