// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Mongodbatlas
{
    public static class GetAiModelApiKeys
    {
        /// <summary>
        /// `mongodbatlas.getAiModelApiKeys` returns all AI Model API Keys for the specified project.
        /// 
        /// &gt; **NOTE:** The `Secret` attribute is not available through this data source as it is only returned during initial creation. To access the secret, use the resource.
        /// 
        /// ## Example Usage
        /// 
        /// ### S
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Mongodbatlas = Pulumi.Mongodbatlas;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var thisAiModelApiKey = new Mongodbatlas.AiModelApiKey("this", new()
        ///     {
        ///         ProjectId = projectId,
        ///         Name = "example-ai-model-key",
        ///         Cloud = "ANY",
        ///         Geography = "ANY",
        ///     });
        /// 
        ///     var @this = Mongodbatlas.GetAiModelApiKey.Invoke(new()
        ///     {
        ///         ProjectId = projectId,
        ///         ApiKeyId = thisAiModelApiKey.ApiKeyId,
        ///     });
        /// 
        ///     var thisGetAiModelApiKeys = Mongodbatlas.GetAiModelApiKeys.Invoke(new()
        ///     {
        ///         ProjectId = projectId,
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["aiModelApiKeyId"] = thisAiModelApiKey.ApiKeyId,
        ///         ["aiModelApiKeySecret"] = thisAiModelApiKey.Secret,
        ///         ["aiModelApiKeyName"] = @this.Apply(@this =&gt; @this.Apply(getAiModelApiKeyResult =&gt; getAiModelApiKeyResult.Name)),
        ///         ["aiModelApiKeyEndpoint"] = @this.Apply(@this =&gt; @this.Apply(getAiModelApiKeyResult =&gt; getAiModelApiKeyResult.Endpoint)),
        ///         ["aiModelApiKeysResults"] = thisGetAiModelApiKeys.Apply(getAiModelApiKeysResult =&gt; getAiModelApiKeysResult.Results),
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Task<GetAiModelApiKeysResult> InvokeAsync(GetAiModelApiKeysArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetAiModelApiKeysResult>("mongodbatlas:index/getAiModelApiKeys:getAiModelApiKeys", args ?? new GetAiModelApiKeysArgs(), options.WithDefaults());

        /// <summary>
        /// `mongodbatlas.getAiModelApiKeys` returns all AI Model API Keys for the specified project.
        /// 
        /// &gt; **NOTE:** The `Secret` attribute is not available through this data source as it is only returned during initial creation. To access the secret, use the resource.
        /// 
        /// ## Example Usage
        /// 
        /// ### S
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Mongodbatlas = Pulumi.Mongodbatlas;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var thisAiModelApiKey = new Mongodbatlas.AiModelApiKey("this", new()
        ///     {
        ///         ProjectId = projectId,
        ///         Name = "example-ai-model-key",
        ///         Cloud = "ANY",
        ///         Geography = "ANY",
        ///     });
        /// 
        ///     var @this = Mongodbatlas.GetAiModelApiKey.Invoke(new()
        ///     {
        ///         ProjectId = projectId,
        ///         ApiKeyId = thisAiModelApiKey.ApiKeyId,
        ///     });
        /// 
        ///     var thisGetAiModelApiKeys = Mongodbatlas.GetAiModelApiKeys.Invoke(new()
        ///     {
        ///         ProjectId = projectId,
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["aiModelApiKeyId"] = thisAiModelApiKey.ApiKeyId,
        ///         ["aiModelApiKeySecret"] = thisAiModelApiKey.Secret,
        ///         ["aiModelApiKeyName"] = @this.Apply(@this =&gt; @this.Apply(getAiModelApiKeyResult =&gt; getAiModelApiKeyResult.Name)),
        ///         ["aiModelApiKeyEndpoint"] = @this.Apply(@this =&gt; @this.Apply(getAiModelApiKeyResult =&gt; getAiModelApiKeyResult.Endpoint)),
        ///         ["aiModelApiKeysResults"] = thisGetAiModelApiKeys.Apply(getAiModelApiKeysResult =&gt; getAiModelApiKeysResult.Results),
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Output<GetAiModelApiKeysResult> Invoke(GetAiModelApiKeysInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetAiModelApiKeysResult>("mongodbatlas:index/getAiModelApiKeys:getAiModelApiKeys", args ?? new GetAiModelApiKeysInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// `mongodbatlas.getAiModelApiKeys` returns all AI Model API Keys for the specified project.
        /// 
        /// &gt; **NOTE:** The `Secret` attribute is not available through this data source as it is only returned during initial creation. To access the secret, use the resource.
        /// 
        /// ## Example Usage
        /// 
        /// ### S
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Mongodbatlas = Pulumi.Mongodbatlas;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var thisAiModelApiKey = new Mongodbatlas.AiModelApiKey("this", new()
        ///     {
        ///         ProjectId = projectId,
        ///         Name = "example-ai-model-key",
        ///         Cloud = "ANY",
        ///         Geography = "ANY",
        ///     });
        /// 
        ///     var @this = Mongodbatlas.GetAiModelApiKey.Invoke(new()
        ///     {
        ///         ProjectId = projectId,
        ///         ApiKeyId = thisAiModelApiKey.ApiKeyId,
        ///     });
        /// 
        ///     var thisGetAiModelApiKeys = Mongodbatlas.GetAiModelApiKeys.Invoke(new()
        ///     {
        ///         ProjectId = projectId,
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["aiModelApiKeyId"] = thisAiModelApiKey.ApiKeyId,
        ///         ["aiModelApiKeySecret"] = thisAiModelApiKey.Secret,
        ///         ["aiModelApiKeyName"] = @this.Apply(@this =&gt; @this.Apply(getAiModelApiKeyResult =&gt; getAiModelApiKeyResult.Name)),
        ///         ["aiModelApiKeyEndpoint"] = @this.Apply(@this =&gt; @this.Apply(getAiModelApiKeyResult =&gt; getAiModelApiKeyResult.Endpoint)),
        ///         ["aiModelApiKeysResults"] = thisGetAiModelApiKeys.Apply(getAiModelApiKeysResult =&gt; getAiModelApiKeysResult.Results),
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Output<GetAiModelApiKeysResult> Invoke(GetAiModelApiKeysInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetAiModelApiKeysResult>("mongodbatlas:index/getAiModelApiKeys:getAiModelApiKeys", args ?? new GetAiModelApiKeysInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetAiModelApiKeysArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Unique 24-hexadecimal digit string that identifies your project, also known as `groupId` in the official documentation.
        /// </summary>
        [Input("projectId", required: true)]
        public string ProjectId { get; set; } = null!;

        public GetAiModelApiKeysArgs()
        {
        }
        public static new GetAiModelApiKeysArgs Empty => new GetAiModelApiKeysArgs();
    }

    public sealed class GetAiModelApiKeysInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Unique 24-hexadecimal digit string that identifies your project, also known as `groupId` in the official documentation.
        /// </summary>
        [Input("projectId", required: true)]
        public Input<string> ProjectId { get; set; } = null!;

        public GetAiModelApiKeysInvokeArgs()
        {
        }
        public static new GetAiModelApiKeysInvokeArgs Empty => new GetAiModelApiKeysInvokeArgs();
    }


    [OutputType]
    public sealed class GetAiModelApiKeysResult
    {
        /// <summary>
        /// Unique 24-hexadecimal digit string that identifies your project, also known as `groupId` in the official documentation.
        /// </summary>
        public readonly string ProjectId;
        /// <summary>
        /// List of returned documents that MongoDB Cloud provides when completing this request.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetAiModelApiKeysResultResult> Results;

        [OutputConstructor]
        private GetAiModelApiKeysResult(
            string projectId,

            ImmutableArray<Outputs.GetAiModelApiKeysResultResult> results)
        {
            ProjectId = projectId;
            Results = results;
        }
    }
}
