// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Mongodbatlas
{
    public static class GetServiceAccountAccessListEntries
    {
        /// <summary>
        /// ## Example Usage
        /// 
        /// ### S
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Mongodbatlas = Pulumi.Mongodbatlas;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var thisServiceAccount = new Mongodbatlas.ServiceAccount("this", new()
        ///     {
        ///         OrgId = orgId,
        ///         Name = "example-service-account",
        ///         Description = "Example Service Account",
        ///         Roles = new[]
        ///         {
        ///             "ORG_READ_ONLY",
        ///         },
        ///         SecretExpiresAfterHours = 2160,
        ///     });
        /// 
        ///     // Add IP Access List Entry to Service Account using CIDR Block
        ///     var cidr = new Mongodbatlas.ServiceAccountAccessListEntry("cidr", new()
        ///     {
        ///         OrgId = orgId,
        ///         ClientId = thisServiceAccount.ClientId,
        ///         CidrBlock = "1.2.3.4/32",
        ///     });
        /// 
        ///     // Add IP Access List Entry to Service Account using IP Address
        ///     var ip = new Mongodbatlas.ServiceAccountAccessListEntry("ip", new()
        ///     {
        ///         OrgId = orgId,
        ///         ClientId = thisServiceAccount.ClientId,
        ///         IpAddress = "2.3.4.5",
        ///     });
        /// 
        ///     // Data source to read a single Access List entry for the Service Account
        ///     var @this = Mongodbatlas.GetServiceAccountAccessListEntry.Invoke(new()
        ///     {
        ///         OrgId = cidr.OrgId,
        ///         ClientId = cidr.ClientId,
        ///         CidrBlock = cidr.CidrBlock,
        ///     });
        /// 
        ///     // Data source to read all Access List entries for the Service Account
        ///     var thisGetServiceAccountAccessListEntries = Mongodbatlas.GetServiceAccountAccessListEntries.Invoke(new()
        ///     {
        ///         OrgId = thisServiceAccount.OrgId,
        ///         ClientId = thisServiceAccount.ClientId,
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["accessListEntryCidrBlock"] = @this.Apply(@this =&gt; @this.Apply(getServiceAccountAccessListEntryResult =&gt; getServiceAccountAccessListEntryResult.CidrBlock)),
        ///         ["allAccessListEntries"] = thisGetServiceAccountAccessListEntries.Apply(getServiceAccountAccessListEntriesResult =&gt; getServiceAccountAccessListEntriesResult.Results),
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Task<GetServiceAccountAccessListEntriesResult> InvokeAsync(GetServiceAccountAccessListEntriesArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetServiceAccountAccessListEntriesResult>("mongodbatlas:index/getServiceAccountAccessListEntries:getServiceAccountAccessListEntries", args ?? new GetServiceAccountAccessListEntriesArgs(), options.WithDefaults());

        /// <summary>
        /// ## Example Usage
        /// 
        /// ### S
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Mongodbatlas = Pulumi.Mongodbatlas;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var thisServiceAccount = new Mongodbatlas.ServiceAccount("this", new()
        ///     {
        ///         OrgId = orgId,
        ///         Name = "example-service-account",
        ///         Description = "Example Service Account",
        ///         Roles = new[]
        ///         {
        ///             "ORG_READ_ONLY",
        ///         },
        ///         SecretExpiresAfterHours = 2160,
        ///     });
        /// 
        ///     // Add IP Access List Entry to Service Account using CIDR Block
        ///     var cidr = new Mongodbatlas.ServiceAccountAccessListEntry("cidr", new()
        ///     {
        ///         OrgId = orgId,
        ///         ClientId = thisServiceAccount.ClientId,
        ///         CidrBlock = "1.2.3.4/32",
        ///     });
        /// 
        ///     // Add IP Access List Entry to Service Account using IP Address
        ///     var ip = new Mongodbatlas.ServiceAccountAccessListEntry("ip", new()
        ///     {
        ///         OrgId = orgId,
        ///         ClientId = thisServiceAccount.ClientId,
        ///         IpAddress = "2.3.4.5",
        ///     });
        /// 
        ///     // Data source to read a single Access List entry for the Service Account
        ///     var @this = Mongodbatlas.GetServiceAccountAccessListEntry.Invoke(new()
        ///     {
        ///         OrgId = cidr.OrgId,
        ///         ClientId = cidr.ClientId,
        ///         CidrBlock = cidr.CidrBlock,
        ///     });
        /// 
        ///     // Data source to read all Access List entries for the Service Account
        ///     var thisGetServiceAccountAccessListEntries = Mongodbatlas.GetServiceAccountAccessListEntries.Invoke(new()
        ///     {
        ///         OrgId = thisServiceAccount.OrgId,
        ///         ClientId = thisServiceAccount.ClientId,
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["accessListEntryCidrBlock"] = @this.Apply(@this =&gt; @this.Apply(getServiceAccountAccessListEntryResult =&gt; getServiceAccountAccessListEntryResult.CidrBlock)),
        ///         ["allAccessListEntries"] = thisGetServiceAccountAccessListEntries.Apply(getServiceAccountAccessListEntriesResult =&gt; getServiceAccountAccessListEntriesResult.Results),
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Output<GetServiceAccountAccessListEntriesResult> Invoke(GetServiceAccountAccessListEntriesInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetServiceAccountAccessListEntriesResult>("mongodbatlas:index/getServiceAccountAccessListEntries:getServiceAccountAccessListEntries", args ?? new GetServiceAccountAccessListEntriesInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// ## Example Usage
        /// 
        /// ### S
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Mongodbatlas = Pulumi.Mongodbatlas;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var thisServiceAccount = new Mongodbatlas.ServiceAccount("this", new()
        ///     {
        ///         OrgId = orgId,
        ///         Name = "example-service-account",
        ///         Description = "Example Service Account",
        ///         Roles = new[]
        ///         {
        ///             "ORG_READ_ONLY",
        ///         },
        ///         SecretExpiresAfterHours = 2160,
        ///     });
        /// 
        ///     // Add IP Access List Entry to Service Account using CIDR Block
        ///     var cidr = new Mongodbatlas.ServiceAccountAccessListEntry("cidr", new()
        ///     {
        ///         OrgId = orgId,
        ///         ClientId = thisServiceAccount.ClientId,
        ///         CidrBlock = "1.2.3.4/32",
        ///     });
        /// 
        ///     // Add IP Access List Entry to Service Account using IP Address
        ///     var ip = new Mongodbatlas.ServiceAccountAccessListEntry("ip", new()
        ///     {
        ///         OrgId = orgId,
        ///         ClientId = thisServiceAccount.ClientId,
        ///         IpAddress = "2.3.4.5",
        ///     });
        /// 
        ///     // Data source to read a single Access List entry for the Service Account
        ///     var @this = Mongodbatlas.GetServiceAccountAccessListEntry.Invoke(new()
        ///     {
        ///         OrgId = cidr.OrgId,
        ///         ClientId = cidr.ClientId,
        ///         CidrBlock = cidr.CidrBlock,
        ///     });
        /// 
        ///     // Data source to read all Access List entries for the Service Account
        ///     var thisGetServiceAccountAccessListEntries = Mongodbatlas.GetServiceAccountAccessListEntries.Invoke(new()
        ///     {
        ///         OrgId = thisServiceAccount.OrgId,
        ///         ClientId = thisServiceAccount.ClientId,
        ///     });
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["accessListEntryCidrBlock"] = @this.Apply(@this =&gt; @this.Apply(getServiceAccountAccessListEntryResult =&gt; getServiceAccountAccessListEntryResult.CidrBlock)),
        ///         ["allAccessListEntries"] = thisGetServiceAccountAccessListEntries.Apply(getServiceAccountAccessListEntriesResult =&gt; getServiceAccountAccessListEntriesResult.Results),
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Output<GetServiceAccountAccessListEntriesResult> Invoke(GetServiceAccountAccessListEntriesInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetServiceAccountAccessListEntriesResult>("mongodbatlas:index/getServiceAccountAccessListEntries:getServiceAccountAccessListEntries", args ?? new GetServiceAccountAccessListEntriesInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetServiceAccountAccessListEntriesArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The Client ID of the Service Account.
        /// </summary>
        [Input("clientId", required: true)]
        public string ClientId { get; set; } = null!;

        /// <summary>
        /// Unique 24-hexadecimal digit string that identifies the organization that contains your projects.
        /// </summary>
        [Input("orgId", required: true)]
        public string OrgId { get; set; } = null!;

        public GetServiceAccountAccessListEntriesArgs()
        {
        }
        public static new GetServiceAccountAccessListEntriesArgs Empty => new GetServiceAccountAccessListEntriesArgs();
    }

    public sealed class GetServiceAccountAccessListEntriesInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The Client ID of the Service Account.
        /// </summary>
        [Input("clientId", required: true)]
        public Input<string> ClientId { get; set; } = null!;

        /// <summary>
        /// Unique 24-hexadecimal digit string that identifies the organization that contains your projects.
        /// </summary>
        [Input("orgId", required: true)]
        public Input<string> OrgId { get; set; } = null!;

        public GetServiceAccountAccessListEntriesInvokeArgs()
        {
        }
        public static new GetServiceAccountAccessListEntriesInvokeArgs Empty => new GetServiceAccountAccessListEntriesInvokeArgs();
    }


    [OutputType]
    public sealed class GetServiceAccountAccessListEntriesResult
    {
        /// <summary>
        /// The Client ID of the Service Account.
        /// </summary>
        public readonly string ClientId;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Unique 24-hexadecimal digit string that identifies the organization that contains your projects.
        /// </summary>
        public readonly string OrgId;
        /// <summary>
        /// List of documents that MongoDB Cloud returns for this request.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetServiceAccountAccessListEntriesResultResult> Results;

        [OutputConstructor]
        private GetServiceAccountAccessListEntriesResult(
            string clientId,

            string id,

            string orgId,

            ImmutableArray<Outputs.GetServiceAccountAccessListEntriesResultResult> results)
        {
            ClientId = clientId;
            Id = id;
            OrgId = orgId;
            Results = results;
        }
    }
}
