// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package mongodbatlas

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// `AlertConfiguration` describes an Alert Configuration.
//
// > **NOTE:** Groups and projects are synonymous terms. You may find **group_id** in the official documentation.
func LookupAlertConfiguration(ctx *pulumi.Context, args *LookupAlertConfigurationArgs, opts ...pulumi.InvokeOption) (*LookupAlertConfigurationResult, error) {
	var rv LookupAlertConfigurationResult
	err := ctx.Invoke("mongodbatlas:index/getAlertConfiguration:getAlertConfiguration", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getAlertConfiguration.
type LookupAlertConfigurationArgs struct {
	// Unique identifier for the alert configuration.
	AlertConfigurationId string `pulumi:"alertConfigurationId"`
	// The ID of the project where the alert configuration will create.
	ProjectId string `pulumi:"projectId"`
}

// A collection of values returned by getAlertConfiguration.
type LookupAlertConfigurationResult struct {
	AlertConfigurationId string `pulumi:"alertConfigurationId"`
	// Timestamp in ISO 8601 date and time format in UTC when this alert configuration was created.
	Created string `pulumi:"created"`
	// If set to true, the alert configuration is enabled. If enabled is not exported it is set to false.
	Enabled bool `pulumi:"enabled"`
	// The type of event that will trigger an alert.
	EventType string `pulumi:"eventType"`
	// The provider-assigned unique ID for this managed resource.
	Id              string                               `pulumi:"id"`
	Matchers        []GetAlertConfigurationMatcher       `pulumi:"matchers"`
	MetricThreshold GetAlertConfigurationMetricThreshold `pulumi:"metricThreshold"`
	Notifications   []GetAlertConfigurationNotification  `pulumi:"notifications"`
	ProjectId       string                               `pulumi:"projectId"`
	// Threshold value outside of which an alert will be triggered.
	Threshold GetAlertConfigurationThreshold `pulumi:"threshold"`
	// Timestamp in ISO 8601 date and time format in UTC when this alert configuration was last updated.
	Updated string `pulumi:"updated"`
}
