// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package mongodbatlas

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// `CloudBackupSnapshotRestoreJob` provides a Cloud Backup Snapshot Restore Job datasource. Gets all the cloud backup snapshot restore jobs for the specified cluster.
//
// > **NOTE:** Groups and projects are synonymous terms. You may find `groupId` in the official documentation.
func LookupCloudBackupSnapshotRestoreJob(ctx *pulumi.Context, args *LookupCloudBackupSnapshotRestoreJobArgs, opts ...pulumi.InvokeOption) (*LookupCloudBackupSnapshotRestoreJobResult, error) {
	var rv LookupCloudBackupSnapshotRestoreJobResult
	err := ctx.Invoke("mongodbatlas:index/getCloudBackupSnapshotRestoreJob:getCloudBackupSnapshotRestoreJob", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getCloudBackupSnapshotRestoreJob.
type LookupCloudBackupSnapshotRestoreJobArgs struct {
	// The name of the Atlas cluster for which you want to retrieve the restore job.
	ClusterName string `pulumi:"clusterName"`
	// The unique identifier of the restore job to retrieve.
	JobId string `pulumi:"jobId"`
	// The unique identifier of the project for the Atlas cluster.
	ProjectId string `pulumi:"projectId"`
}

// A collection of values returned by getCloudBackupSnapshotRestoreJob.
type LookupCloudBackupSnapshotRestoreJobResult struct {
	// Indicates whether the restore job was canceled.
	Cancelled   bool   `pulumi:"cancelled"`
	ClusterName string `pulumi:"clusterName"`
	// UTC ISO 8601 formatted point in time when Atlas created the restore job.
	CreatedAt string `pulumi:"createdAt"`
	// Type of restore job to create. Possible values are: automated and download.
	DeliveryType string `pulumi:"deliveryType"`
	// One or more URLs for the compressed snapshot files for manual download. Only visible if deliveryType is download.
	DeliveryUrls []string `pulumi:"deliveryUrls"`
	// Indicates whether the restore job expired.
	Expired bool `pulumi:"expired"`
	// UTC ISO 8601 formatted point in time when the restore job expires.
	ExpiresAt string `pulumi:"expiresAt"`
	// UTC ISO 8601 formatted point in time when the restore job completed.
	FinishedAt string `pulumi:"finishedAt"`
	// The provider-assigned unique ID for this managed resource.
	Id                    string `pulumi:"id"`
	JobId                 string `pulumi:"jobId"`
	OplogInc              int    `pulumi:"oplogInc"`
	OplogTs               int    `pulumi:"oplogTs"`
	PointInTimeUtcSeconds int    `pulumi:"pointInTimeUtcSeconds"`
	ProjectId             string `pulumi:"projectId"`
	// Unique identifier of the source snapshot ID of the restore job.
	SnapshotId string `pulumi:"snapshotId"`
	// Name of the target Atlas cluster to which the restore job restores the snapshot. Only visible if deliveryType is automated.
	TargetClusterName string `pulumi:"targetClusterName"`
	TargetProjectId   string `pulumi:"targetProjectId"`
	// Timestamp in ISO 8601 date and time format in UTC when the snapshot associated to snapshotId was taken.
	Timestamp string `pulumi:"timestamp"`
}

func LookupCloudBackupSnapshotRestoreJobOutput(ctx *pulumi.Context, args LookupCloudBackupSnapshotRestoreJobOutputArgs, opts ...pulumi.InvokeOption) LookupCloudBackupSnapshotRestoreJobResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupCloudBackupSnapshotRestoreJobResult, error) {
			args := v.(LookupCloudBackupSnapshotRestoreJobArgs)
			r, err := LookupCloudBackupSnapshotRestoreJob(ctx, &args, opts...)
			var s LookupCloudBackupSnapshotRestoreJobResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupCloudBackupSnapshotRestoreJobResultOutput)
}

// A collection of arguments for invoking getCloudBackupSnapshotRestoreJob.
type LookupCloudBackupSnapshotRestoreJobOutputArgs struct {
	// The name of the Atlas cluster for which you want to retrieve the restore job.
	ClusterName pulumi.StringInput `pulumi:"clusterName"`
	// The unique identifier of the restore job to retrieve.
	JobId pulumi.StringInput `pulumi:"jobId"`
	// The unique identifier of the project for the Atlas cluster.
	ProjectId pulumi.StringInput `pulumi:"projectId"`
}

func (LookupCloudBackupSnapshotRestoreJobOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupCloudBackupSnapshotRestoreJobArgs)(nil)).Elem()
}

// A collection of values returned by getCloudBackupSnapshotRestoreJob.
type LookupCloudBackupSnapshotRestoreJobResultOutput struct{ *pulumi.OutputState }

func (LookupCloudBackupSnapshotRestoreJobResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupCloudBackupSnapshotRestoreJobResult)(nil)).Elem()
}

func (o LookupCloudBackupSnapshotRestoreJobResultOutput) ToLookupCloudBackupSnapshotRestoreJobResultOutput() LookupCloudBackupSnapshotRestoreJobResultOutput {
	return o
}

func (o LookupCloudBackupSnapshotRestoreJobResultOutput) ToLookupCloudBackupSnapshotRestoreJobResultOutputWithContext(ctx context.Context) LookupCloudBackupSnapshotRestoreJobResultOutput {
	return o
}

// Indicates whether the restore job was canceled.
func (o LookupCloudBackupSnapshotRestoreJobResultOutput) Cancelled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupCloudBackupSnapshotRestoreJobResult) bool { return v.Cancelled }).(pulumi.BoolOutput)
}

func (o LookupCloudBackupSnapshotRestoreJobResultOutput) ClusterName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudBackupSnapshotRestoreJobResult) string { return v.ClusterName }).(pulumi.StringOutput)
}

// UTC ISO 8601 formatted point in time when Atlas created the restore job.
func (o LookupCloudBackupSnapshotRestoreJobResultOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudBackupSnapshotRestoreJobResult) string { return v.CreatedAt }).(pulumi.StringOutput)
}

// Type of restore job to create. Possible values are: automated and download.
func (o LookupCloudBackupSnapshotRestoreJobResultOutput) DeliveryType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudBackupSnapshotRestoreJobResult) string { return v.DeliveryType }).(pulumi.StringOutput)
}

// One or more URLs for the compressed snapshot files for manual download. Only visible if deliveryType is download.
func (o LookupCloudBackupSnapshotRestoreJobResultOutput) DeliveryUrls() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupCloudBackupSnapshotRestoreJobResult) []string { return v.DeliveryUrls }).(pulumi.StringArrayOutput)
}

// Indicates whether the restore job expired.
func (o LookupCloudBackupSnapshotRestoreJobResultOutput) Expired() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupCloudBackupSnapshotRestoreJobResult) bool { return v.Expired }).(pulumi.BoolOutput)
}

// UTC ISO 8601 formatted point in time when the restore job expires.
func (o LookupCloudBackupSnapshotRestoreJobResultOutput) ExpiresAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudBackupSnapshotRestoreJobResult) string { return v.ExpiresAt }).(pulumi.StringOutput)
}

// UTC ISO 8601 formatted point in time when the restore job completed.
func (o LookupCloudBackupSnapshotRestoreJobResultOutput) FinishedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudBackupSnapshotRestoreJobResult) string { return v.FinishedAt }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupCloudBackupSnapshotRestoreJobResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudBackupSnapshotRestoreJobResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupCloudBackupSnapshotRestoreJobResultOutput) JobId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudBackupSnapshotRestoreJobResult) string { return v.JobId }).(pulumi.StringOutput)
}

func (o LookupCloudBackupSnapshotRestoreJobResultOutput) OplogInc() pulumi.IntOutput {
	return o.ApplyT(func(v LookupCloudBackupSnapshotRestoreJobResult) int { return v.OplogInc }).(pulumi.IntOutput)
}

func (o LookupCloudBackupSnapshotRestoreJobResultOutput) OplogTs() pulumi.IntOutput {
	return o.ApplyT(func(v LookupCloudBackupSnapshotRestoreJobResult) int { return v.OplogTs }).(pulumi.IntOutput)
}

func (o LookupCloudBackupSnapshotRestoreJobResultOutput) PointInTimeUtcSeconds() pulumi.IntOutput {
	return o.ApplyT(func(v LookupCloudBackupSnapshotRestoreJobResult) int { return v.PointInTimeUtcSeconds }).(pulumi.IntOutput)
}

func (o LookupCloudBackupSnapshotRestoreJobResultOutput) ProjectId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudBackupSnapshotRestoreJobResult) string { return v.ProjectId }).(pulumi.StringOutput)
}

// Unique identifier of the source snapshot ID of the restore job.
func (o LookupCloudBackupSnapshotRestoreJobResultOutput) SnapshotId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudBackupSnapshotRestoreJobResult) string { return v.SnapshotId }).(pulumi.StringOutput)
}

// Name of the target Atlas cluster to which the restore job restores the snapshot. Only visible if deliveryType is automated.
func (o LookupCloudBackupSnapshotRestoreJobResultOutput) TargetClusterName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudBackupSnapshotRestoreJobResult) string { return v.TargetClusterName }).(pulumi.StringOutput)
}

func (o LookupCloudBackupSnapshotRestoreJobResultOutput) TargetProjectId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudBackupSnapshotRestoreJobResult) string { return v.TargetProjectId }).(pulumi.StringOutput)
}

// Timestamp in ISO 8601 date and time format in UTC when the snapshot associated to snapshotId was taken.
func (o LookupCloudBackupSnapshotRestoreJobResultOutput) Timestamp() pulumi.StringOutput {
	return o.ApplyT(func(v LookupCloudBackupSnapshotRestoreJobResult) string { return v.Timestamp }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupCloudBackupSnapshotRestoreJobResultOutput{})
}
