// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package mongodbatlas

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-mongodbatlas/sdk/v4/go/mongodbatlas/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// `getLogIntegrations` describes all log integrations configured at the project level. Supported integration types include AWS S3, Google Cloud Storage, Azure Blob Storage, Datadog, Splunk, and OpenTelemetry.
//
// To use this data source, the requesting Service Account or API Key must have the Organization Owner or Project Owner role.
//
// ## Example Usage
//
// ### Further Examples
// - Log Integration Examples
func LookupLogIntegrations(ctx *pulumi.Context, args *LookupLogIntegrationsArgs, opts ...pulumi.InvokeOption) (*LookupLogIntegrationsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupLogIntegrationsResult
	err := ctx.Invoke("mongodbatlas:index/getLogIntegrations:getLogIntegrations", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getLogIntegrations.
type LookupLogIntegrationsArgs struct {
	// Optional filter by integration type (e.g., `S3_LOG_EXPORT`).
	IntegrationType *string `pulumi:"integrationType"`
	// Unique 24-hexadecimal digit string that identifies your project, also known as `groupId` in the official documentation.
	ProjectId string `pulumi:"projectId"`
}

// A collection of values returned by getLogIntegrations.
type LookupLogIntegrationsResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// Optional filter by integration type (e.g., `S3_LOG_EXPORT`).
	IntegrationType *string `pulumi:"integrationType"`
	// Unique 24-hexadecimal digit string that identifies your project, also known as `groupId` in the official documentation.
	ProjectId string `pulumi:"projectId"`
	// List of returned documents that MongoDB Cloud provides when completing this request.
	Results []GetLogIntegrationsResult `pulumi:"results"`
}

func LookupLogIntegrationsOutput(ctx *pulumi.Context, args LookupLogIntegrationsOutputArgs, opts ...pulumi.InvokeOption) LookupLogIntegrationsResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupLogIntegrationsResultOutput, error) {
			args := v.(LookupLogIntegrationsArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("mongodbatlas:index/getLogIntegrations:getLogIntegrations", args, LookupLogIntegrationsResultOutput{}, options).(LookupLogIntegrationsResultOutput), nil
		}).(LookupLogIntegrationsResultOutput)
}

// A collection of arguments for invoking getLogIntegrations.
type LookupLogIntegrationsOutputArgs struct {
	// Optional filter by integration type (e.g., `S3_LOG_EXPORT`).
	IntegrationType pulumi.StringPtrInput `pulumi:"integrationType"`
	// Unique 24-hexadecimal digit string that identifies your project, also known as `groupId` in the official documentation.
	ProjectId pulumi.StringInput `pulumi:"projectId"`
}

func (LookupLogIntegrationsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupLogIntegrationsArgs)(nil)).Elem()
}

// A collection of values returned by getLogIntegrations.
type LookupLogIntegrationsResultOutput struct{ *pulumi.OutputState }

func (LookupLogIntegrationsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupLogIntegrationsResult)(nil)).Elem()
}

func (o LookupLogIntegrationsResultOutput) ToLookupLogIntegrationsResultOutput() LookupLogIntegrationsResultOutput {
	return o
}

func (o LookupLogIntegrationsResultOutput) ToLookupLogIntegrationsResultOutputWithContext(ctx context.Context) LookupLogIntegrationsResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o LookupLogIntegrationsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupLogIntegrationsResult) string { return v.Id }).(pulumi.StringOutput)
}

// Optional filter by integration type (e.g., `S3_LOG_EXPORT`).
func (o LookupLogIntegrationsResultOutput) IntegrationType() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupLogIntegrationsResult) *string { return v.IntegrationType }).(pulumi.StringPtrOutput)
}

// Unique 24-hexadecimal digit string that identifies your project, also known as `groupId` in the official documentation.
func (o LookupLogIntegrationsResultOutput) ProjectId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupLogIntegrationsResult) string { return v.ProjectId }).(pulumi.StringOutput)
}

// List of returned documents that MongoDB Cloud provides when completing this request.
func (o LookupLogIntegrationsResultOutput) Results() GetLogIntegrationsResultArrayOutput {
	return o.ApplyT(func(v LookupLogIntegrationsResult) []GetLogIntegrationsResult { return v.Results }).(GetLogIntegrationsResultArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupLogIntegrationsResultOutput{})
}
