// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package mongodbatlas

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-mongodbatlas/sdk/v4/go/mongodbatlas/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// ## Example Usage
//
// ### S
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-mongodbatlas/sdk/v4/go/mongodbatlas"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			thisProjectServiceAccount, err := mongodbatlas.NewProjectServiceAccount(ctx, "this", &mongodbatlas.ProjectServiceAccountArgs{
//				ProjectId:   pulumi.Any(projectId),
//				Name:        pulumi.String("example-project-service-account"),
//				Description: pulumi.String("Example Project Service Account"),
//				Roles: pulumi.StringArray{
//					pulumi.String("GROUP_READ_ONLY"),
//				},
//				SecretExpiresAfterHours: pulumi.Int(2160),
//			})
//			if err != nil {
//				return err
//			}
//			thisProjectServiceAccountSecret, err := mongodbatlas.NewProjectServiceAccountSecret(ctx, "this", &mongodbatlas.ProjectServiceAccountSecretArgs{
//				ProjectId:               pulumi.Any(projectId),
//				ClientId:                thisProjectServiceAccount.ClientId,
//				SecretExpiresAfterHours: pulumi.Int(2160),
//			})
//			if err != nil {
//				return err
//			}
//			this := pulumi.All(thisProjectServiceAccount.ClientId, thisProjectServiceAccountSecret.SecretId).ApplyT(func(_args []interface{}) (mongodbatlas.GetProjectServiceAccountSecretResult, error) {
//				clientId := _args[0].(string)
//				secretId := _args[1].(string)
//				return mongodbatlas.GetProjectServiceAccountSecretResult(interface{}(mongodbatlas.LookupProjectServiceAccountSecret(ctx, &mongodbatlas.LookupProjectServiceAccountSecretArgs{
//					ProjectId: projectId,
//					ClientId:  clientId,
//					SecretId:  secretId,
//				}, nil))), nil
//			}).(mongodbatlas.GetProjectServiceAccountSecretResultOutput)
//			ctx.Export("secretId", thisProjectServiceAccountSecret.SecretId)
//			ctx.Export("secret", thisProjectServiceAccountSecret.Secret)
//			ctx.Export("secretExpiresAt", this.ApplyT(func(this mongodbatlas.GetProjectServiceAccountSecretResult) (*string, error) {
//				return &this.ExpiresAt, nil
//			}).(pulumi.StringPtrOutput))
//			return nil
//		})
//	}
//
// ```
func LookupProjectServiceAccountSecret(ctx *pulumi.Context, args *LookupProjectServiceAccountSecretArgs, opts ...pulumi.InvokeOption) (*LookupProjectServiceAccountSecretResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupProjectServiceAccountSecretResult
	err := ctx.Invoke("mongodbatlas:index/getProjectServiceAccountSecret:getProjectServiceAccountSecret", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getProjectServiceAccountSecret.
type LookupProjectServiceAccountSecretArgs struct {
	// The Client ID of the Service Account.
	ClientId string `pulumi:"clientId"`
	// Unique 24-hexadecimal digit string that identifies your project.
	ProjectId string `pulumi:"projectId"`
	// Unique 24-hexadecimal digit string that identifies the secret.
	SecretId string `pulumi:"secretId"`
}

// A collection of values returned by getProjectServiceAccountSecret.
type LookupProjectServiceAccountSecretResult struct {
	// The Client ID of the Service Account.
	ClientId string `pulumi:"clientId"`
	// The date that the secret was created on. This parameter expresses its value in the ISO 8601 timestamp format in UTC.
	CreatedAt string `pulumi:"createdAt"`
	// The date for the expiration of the secret. This parameter expresses its value in the ISO 8601 timestamp format in UTC.
	ExpiresAt string `pulumi:"expiresAt"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// The last time the secret was used. This parameter expresses its value in the ISO 8601 timestamp format in UTC.
	LastUsedAt string `pulumi:"lastUsedAt"`
	// The masked Service Account secret.
	MaskedSecretValue string `pulumi:"maskedSecretValue"`
	// Unique 24-hexadecimal digit string that identifies your project.
	ProjectId string `pulumi:"projectId"`
	// Unique 24-hexadecimal digit string that identifies the secret.
	SecretId string `pulumi:"secretId"`
}

func LookupProjectServiceAccountSecretOutput(ctx *pulumi.Context, args LookupProjectServiceAccountSecretOutputArgs, opts ...pulumi.InvokeOption) LookupProjectServiceAccountSecretResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupProjectServiceAccountSecretResultOutput, error) {
			args := v.(LookupProjectServiceAccountSecretArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("mongodbatlas:index/getProjectServiceAccountSecret:getProjectServiceAccountSecret", args, LookupProjectServiceAccountSecretResultOutput{}, options).(LookupProjectServiceAccountSecretResultOutput), nil
		}).(LookupProjectServiceAccountSecretResultOutput)
}

// A collection of arguments for invoking getProjectServiceAccountSecret.
type LookupProjectServiceAccountSecretOutputArgs struct {
	// The Client ID of the Service Account.
	ClientId pulumi.StringInput `pulumi:"clientId"`
	// Unique 24-hexadecimal digit string that identifies your project.
	ProjectId pulumi.StringInput `pulumi:"projectId"`
	// Unique 24-hexadecimal digit string that identifies the secret.
	SecretId pulumi.StringInput `pulumi:"secretId"`
}

func (LookupProjectServiceAccountSecretOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupProjectServiceAccountSecretArgs)(nil)).Elem()
}

// A collection of values returned by getProjectServiceAccountSecret.
type LookupProjectServiceAccountSecretResultOutput struct{ *pulumi.OutputState }

func (LookupProjectServiceAccountSecretResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupProjectServiceAccountSecretResult)(nil)).Elem()
}

func (o LookupProjectServiceAccountSecretResultOutput) ToLookupProjectServiceAccountSecretResultOutput() LookupProjectServiceAccountSecretResultOutput {
	return o
}

func (o LookupProjectServiceAccountSecretResultOutput) ToLookupProjectServiceAccountSecretResultOutputWithContext(ctx context.Context) LookupProjectServiceAccountSecretResultOutput {
	return o
}

// The Client ID of the Service Account.
func (o LookupProjectServiceAccountSecretResultOutput) ClientId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupProjectServiceAccountSecretResult) string { return v.ClientId }).(pulumi.StringOutput)
}

// The date that the secret was created on. This parameter expresses its value in the ISO 8601 timestamp format in UTC.
func (o LookupProjectServiceAccountSecretResultOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupProjectServiceAccountSecretResult) string { return v.CreatedAt }).(pulumi.StringOutput)
}

// The date for the expiration of the secret. This parameter expresses its value in the ISO 8601 timestamp format in UTC.
func (o LookupProjectServiceAccountSecretResultOutput) ExpiresAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupProjectServiceAccountSecretResult) string { return v.ExpiresAt }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupProjectServiceAccountSecretResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupProjectServiceAccountSecretResult) string { return v.Id }).(pulumi.StringOutput)
}

// The last time the secret was used. This parameter expresses its value in the ISO 8601 timestamp format in UTC.
func (o LookupProjectServiceAccountSecretResultOutput) LastUsedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupProjectServiceAccountSecretResult) string { return v.LastUsedAt }).(pulumi.StringOutput)
}

// The masked Service Account secret.
func (o LookupProjectServiceAccountSecretResultOutput) MaskedSecretValue() pulumi.StringOutput {
	return o.ApplyT(func(v LookupProjectServiceAccountSecretResult) string { return v.MaskedSecretValue }).(pulumi.StringOutput)
}

// Unique 24-hexadecimal digit string that identifies your project.
func (o LookupProjectServiceAccountSecretResultOutput) ProjectId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupProjectServiceAccountSecretResult) string { return v.ProjectId }).(pulumi.StringOutput)
}

// Unique 24-hexadecimal digit string that identifies the secret.
func (o LookupProjectServiceAccountSecretResultOutput) SecretId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupProjectServiceAccountSecretResult) string { return v.SecretId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupProjectServiceAccountSecretResultOutput{})
}
