// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package mongodbatlas

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-mongodbatlas/sdk/v4/go/mongodbatlas/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// `ProjectServiceAccount` provides a Project Service Account resource. The resource lets you create, update, delete, and import a Service Account for the specified Project.
//
// > **IMPORTANT WARNING:** Managing Service Accounts with Terraform **exposes sensitive organizational secrets** in Terraform's state. We suggest following Terraform's best practices.
//
// > **IMPORTANT:** The use of `ProjectServiceAccount` resource is not recommended for users with Organization Owner permissions. Instead, use the `ServiceAccount` and `ServiceAccountProjectAssignment` resources to manage Service Account project assignments.
//
// > **IMPORTANT:** Deleting a `ProjectServiceAccount` resource unassigns the associated Service Account from the project, but doesn't delete it from the organization.
//
// ## Example Usage
//
// ## Import
//
// Import the Project Service Account resource by using the Project ID and Client ID in the format `PROJECT_ID/CLIENT_ID`, e.g.
//
// > **NOTE:** `secretExpiresAfterHours` is not populated during import and should be omitted in the resource definition when importing the resource.
//
// For more information, see [Create One Project Service Account](https://www.mongodb.com/docs/api/doc/atlas-admin-api-v2/operation/operation-creategroupserviceaccount) in the MongoDB Atlas API documentation.
type ProjectServiceAccount struct {
	pulumi.CustomResourceState

	// The Client ID of the Service Account.
	ClientId pulumi.StringOutput `pulumi:"clientId"`
	// The date that the Service Account was created on. This parameter expresses its value in the ISO 8601 timestamp format in UTC.
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// Human readable description for the Service Account.
	Description pulumi.StringOutput `pulumi:"description"`
	// Human-readable name for the Service Account. The name is modifiable and does not have to be unique.
	Name pulumi.StringOutput `pulumi:"name"`
	// Unique 24-hexadecimal digit string that identifies your project.
	ProjectId pulumi.StringOutput `pulumi:"projectId"`
	// A list of project-level roles for the Service Account.
	Roles pulumi.StringArrayOutput `pulumi:"roles"`
	// The expiration time of the new Service Account secret, provided in hours. The minimum and maximum allowed expiration times are subject to change and are controlled by the organization's settings. This attribute is required when creating the Service Account and you cannot update it later.
	SecretExpiresAfterHours pulumi.IntPtrOutput `pulumi:"secretExpiresAfterHours"`
	// A list of secrets associated with the specified Service Account.
	Secrets ProjectServiceAccountSecretTypeArrayOutput `pulumi:"secrets"`
}

// NewProjectServiceAccount registers a new resource with the given unique name, arguments, and options.
func NewProjectServiceAccount(ctx *pulumi.Context,
	name string, args *ProjectServiceAccountArgs, opts ...pulumi.ResourceOption) (*ProjectServiceAccount, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Description == nil {
		return nil, errors.New("invalid value for required argument 'Description'")
	}
	if args.ProjectId == nil {
		return nil, errors.New("invalid value for required argument 'ProjectId'")
	}
	if args.Roles == nil {
		return nil, errors.New("invalid value for required argument 'Roles'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ProjectServiceAccount
	err := ctx.RegisterResource("mongodbatlas:index/projectServiceAccount:ProjectServiceAccount", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetProjectServiceAccount gets an existing ProjectServiceAccount resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetProjectServiceAccount(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ProjectServiceAccountState, opts ...pulumi.ResourceOption) (*ProjectServiceAccount, error) {
	var resource ProjectServiceAccount
	err := ctx.ReadResource("mongodbatlas:index/projectServiceAccount:ProjectServiceAccount", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ProjectServiceAccount resources.
type projectServiceAccountState struct {
	// The Client ID of the Service Account.
	ClientId *string `pulumi:"clientId"`
	// The date that the Service Account was created on. This parameter expresses its value in the ISO 8601 timestamp format in UTC.
	CreatedAt *string `pulumi:"createdAt"`
	// Human readable description for the Service Account.
	Description *string `pulumi:"description"`
	// Human-readable name for the Service Account. The name is modifiable and does not have to be unique.
	Name *string `pulumi:"name"`
	// Unique 24-hexadecimal digit string that identifies your project.
	ProjectId *string `pulumi:"projectId"`
	// A list of project-level roles for the Service Account.
	Roles []string `pulumi:"roles"`
	// The expiration time of the new Service Account secret, provided in hours. The minimum and maximum allowed expiration times are subject to change and are controlled by the organization's settings. This attribute is required when creating the Service Account and you cannot update it later.
	SecretExpiresAfterHours *int `pulumi:"secretExpiresAfterHours"`
	// A list of secrets associated with the specified Service Account.
	Secrets []ProjectServiceAccountSecretType `pulumi:"secrets"`
}

type ProjectServiceAccountState struct {
	// The Client ID of the Service Account.
	ClientId pulumi.StringPtrInput
	// The date that the Service Account was created on. This parameter expresses its value in the ISO 8601 timestamp format in UTC.
	CreatedAt pulumi.StringPtrInput
	// Human readable description for the Service Account.
	Description pulumi.StringPtrInput
	// Human-readable name for the Service Account. The name is modifiable and does not have to be unique.
	Name pulumi.StringPtrInput
	// Unique 24-hexadecimal digit string that identifies your project.
	ProjectId pulumi.StringPtrInput
	// A list of project-level roles for the Service Account.
	Roles pulumi.StringArrayInput
	// The expiration time of the new Service Account secret, provided in hours. The minimum and maximum allowed expiration times are subject to change and are controlled by the organization's settings. This attribute is required when creating the Service Account and you cannot update it later.
	SecretExpiresAfterHours pulumi.IntPtrInput
	// A list of secrets associated with the specified Service Account.
	Secrets ProjectServiceAccountSecretTypeArrayInput
}

func (ProjectServiceAccountState) ElementType() reflect.Type {
	return reflect.TypeOf((*projectServiceAccountState)(nil)).Elem()
}

type projectServiceAccountArgs struct {
	// Human readable description for the Service Account.
	Description string `pulumi:"description"`
	// Human-readable name for the Service Account. The name is modifiable and does not have to be unique.
	Name *string `pulumi:"name"`
	// Unique 24-hexadecimal digit string that identifies your project.
	ProjectId string `pulumi:"projectId"`
	// A list of project-level roles for the Service Account.
	Roles []string `pulumi:"roles"`
	// The expiration time of the new Service Account secret, provided in hours. The minimum and maximum allowed expiration times are subject to change and are controlled by the organization's settings. This attribute is required when creating the Service Account and you cannot update it later.
	SecretExpiresAfterHours *int `pulumi:"secretExpiresAfterHours"`
}

// The set of arguments for constructing a ProjectServiceAccount resource.
type ProjectServiceAccountArgs struct {
	// Human readable description for the Service Account.
	Description pulumi.StringInput
	// Human-readable name for the Service Account. The name is modifiable and does not have to be unique.
	Name pulumi.StringPtrInput
	// Unique 24-hexadecimal digit string that identifies your project.
	ProjectId pulumi.StringInput
	// A list of project-level roles for the Service Account.
	Roles pulumi.StringArrayInput
	// The expiration time of the new Service Account secret, provided in hours. The minimum and maximum allowed expiration times are subject to change and are controlled by the organization's settings. This attribute is required when creating the Service Account and you cannot update it later.
	SecretExpiresAfterHours pulumi.IntPtrInput
}

func (ProjectServiceAccountArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*projectServiceAccountArgs)(nil)).Elem()
}

type ProjectServiceAccountInput interface {
	pulumi.Input

	ToProjectServiceAccountOutput() ProjectServiceAccountOutput
	ToProjectServiceAccountOutputWithContext(ctx context.Context) ProjectServiceAccountOutput
}

func (*ProjectServiceAccount) ElementType() reflect.Type {
	return reflect.TypeOf((**ProjectServiceAccount)(nil)).Elem()
}

func (i *ProjectServiceAccount) ToProjectServiceAccountOutput() ProjectServiceAccountOutput {
	return i.ToProjectServiceAccountOutputWithContext(context.Background())
}

func (i *ProjectServiceAccount) ToProjectServiceAccountOutputWithContext(ctx context.Context) ProjectServiceAccountOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProjectServiceAccountOutput)
}

// ProjectServiceAccountArrayInput is an input type that accepts ProjectServiceAccountArray and ProjectServiceAccountArrayOutput values.
// You can construct a concrete instance of `ProjectServiceAccountArrayInput` via:
//
//	ProjectServiceAccountArray{ ProjectServiceAccountArgs{...} }
type ProjectServiceAccountArrayInput interface {
	pulumi.Input

	ToProjectServiceAccountArrayOutput() ProjectServiceAccountArrayOutput
	ToProjectServiceAccountArrayOutputWithContext(context.Context) ProjectServiceAccountArrayOutput
}

type ProjectServiceAccountArray []ProjectServiceAccountInput

func (ProjectServiceAccountArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ProjectServiceAccount)(nil)).Elem()
}

func (i ProjectServiceAccountArray) ToProjectServiceAccountArrayOutput() ProjectServiceAccountArrayOutput {
	return i.ToProjectServiceAccountArrayOutputWithContext(context.Background())
}

func (i ProjectServiceAccountArray) ToProjectServiceAccountArrayOutputWithContext(ctx context.Context) ProjectServiceAccountArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProjectServiceAccountArrayOutput)
}

// ProjectServiceAccountMapInput is an input type that accepts ProjectServiceAccountMap and ProjectServiceAccountMapOutput values.
// You can construct a concrete instance of `ProjectServiceAccountMapInput` via:
//
//	ProjectServiceAccountMap{ "key": ProjectServiceAccountArgs{...} }
type ProjectServiceAccountMapInput interface {
	pulumi.Input

	ToProjectServiceAccountMapOutput() ProjectServiceAccountMapOutput
	ToProjectServiceAccountMapOutputWithContext(context.Context) ProjectServiceAccountMapOutput
}

type ProjectServiceAccountMap map[string]ProjectServiceAccountInput

func (ProjectServiceAccountMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ProjectServiceAccount)(nil)).Elem()
}

func (i ProjectServiceAccountMap) ToProjectServiceAccountMapOutput() ProjectServiceAccountMapOutput {
	return i.ToProjectServiceAccountMapOutputWithContext(context.Background())
}

func (i ProjectServiceAccountMap) ToProjectServiceAccountMapOutputWithContext(ctx context.Context) ProjectServiceAccountMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProjectServiceAccountMapOutput)
}

type ProjectServiceAccountOutput struct{ *pulumi.OutputState }

func (ProjectServiceAccountOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ProjectServiceAccount)(nil)).Elem()
}

func (o ProjectServiceAccountOutput) ToProjectServiceAccountOutput() ProjectServiceAccountOutput {
	return o
}

func (o ProjectServiceAccountOutput) ToProjectServiceAccountOutputWithContext(ctx context.Context) ProjectServiceAccountOutput {
	return o
}

// The Client ID of the Service Account.
func (o ProjectServiceAccountOutput) ClientId() pulumi.StringOutput {
	return o.ApplyT(func(v *ProjectServiceAccount) pulumi.StringOutput { return v.ClientId }).(pulumi.StringOutput)
}

// The date that the Service Account was created on. This parameter expresses its value in the ISO 8601 timestamp format in UTC.
func (o ProjectServiceAccountOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *ProjectServiceAccount) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// Human readable description for the Service Account.
func (o ProjectServiceAccountOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v *ProjectServiceAccount) pulumi.StringOutput { return v.Description }).(pulumi.StringOutput)
}

// Human-readable name for the Service Account. The name is modifiable and does not have to be unique.
func (o ProjectServiceAccountOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *ProjectServiceAccount) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Unique 24-hexadecimal digit string that identifies your project.
func (o ProjectServiceAccountOutput) ProjectId() pulumi.StringOutput {
	return o.ApplyT(func(v *ProjectServiceAccount) pulumi.StringOutput { return v.ProjectId }).(pulumi.StringOutput)
}

// A list of project-level roles for the Service Account.
func (o ProjectServiceAccountOutput) Roles() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *ProjectServiceAccount) pulumi.StringArrayOutput { return v.Roles }).(pulumi.StringArrayOutput)
}

// The expiration time of the new Service Account secret, provided in hours. The minimum and maximum allowed expiration times are subject to change and are controlled by the organization's settings. This attribute is required when creating the Service Account and you cannot update it later.
func (o ProjectServiceAccountOutput) SecretExpiresAfterHours() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *ProjectServiceAccount) pulumi.IntPtrOutput { return v.SecretExpiresAfterHours }).(pulumi.IntPtrOutput)
}

// A list of secrets associated with the specified Service Account.
func (o ProjectServiceAccountOutput) Secrets() ProjectServiceAccountSecretTypeArrayOutput {
	return o.ApplyT(func(v *ProjectServiceAccount) ProjectServiceAccountSecretTypeArrayOutput { return v.Secrets }).(ProjectServiceAccountSecretTypeArrayOutput)
}

type ProjectServiceAccountArrayOutput struct{ *pulumi.OutputState }

func (ProjectServiceAccountArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ProjectServiceAccount)(nil)).Elem()
}

func (o ProjectServiceAccountArrayOutput) ToProjectServiceAccountArrayOutput() ProjectServiceAccountArrayOutput {
	return o
}

func (o ProjectServiceAccountArrayOutput) ToProjectServiceAccountArrayOutputWithContext(ctx context.Context) ProjectServiceAccountArrayOutput {
	return o
}

func (o ProjectServiceAccountArrayOutput) Index(i pulumi.IntInput) ProjectServiceAccountOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *ProjectServiceAccount {
		return vs[0].([]*ProjectServiceAccount)[vs[1].(int)]
	}).(ProjectServiceAccountOutput)
}

type ProjectServiceAccountMapOutput struct{ *pulumi.OutputState }

func (ProjectServiceAccountMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ProjectServiceAccount)(nil)).Elem()
}

func (o ProjectServiceAccountMapOutput) ToProjectServiceAccountMapOutput() ProjectServiceAccountMapOutput {
	return o
}

func (o ProjectServiceAccountMapOutput) ToProjectServiceAccountMapOutputWithContext(ctx context.Context) ProjectServiceAccountMapOutput {
	return o
}

func (o ProjectServiceAccountMapOutput) MapIndex(k pulumi.StringInput) ProjectServiceAccountOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *ProjectServiceAccount {
		return vs[0].(map[string]*ProjectServiceAccount)[vs[1].(string)]
	}).(ProjectServiceAccountOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ProjectServiceAccountInput)(nil)).Elem(), &ProjectServiceAccount{})
	pulumi.RegisterInputType(reflect.TypeOf((*ProjectServiceAccountArrayInput)(nil)).Elem(), ProjectServiceAccountArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ProjectServiceAccountMapInput)(nil)).Elem(), ProjectServiceAccountMap{})
	pulumi.RegisterOutputType(ProjectServiceAccountOutput{})
	pulumi.RegisterOutputType(ProjectServiceAccountArrayOutput{})
	pulumi.RegisterOutputType(ProjectServiceAccountMapOutput{})
}
