// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.mongodbatlas.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetCloudBackupSnapshotDatabasesArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetCloudBackupSnapshotDatabasesArgs Empty = new GetCloudBackupSnapshotDatabasesArgs();

    /**
     * Human-readable label that identifies the cluster.
     * 
     */
    @Import(name="clusterName", required=true)
    private Output<String> clusterName;

    /**
     * @return Human-readable label that identifies the cluster.
     * 
     */
    public Output<String> clusterName() {
        return this.clusterName;
    }

    /**
     * Unique 24-hexadecimal digit string that identifies your project, also known as `groupId` in the official documentation.
     * 
     */
    @Import(name="projectId", required=true)
    private Output<String> projectId;

    /**
     * @return Unique 24-hexadecimal digit string that identifies your project, also known as `groupId` in the official documentation.
     * 
     */
    public Output<String> projectId() {
        return this.projectId;
    }

    /**
     * Unique 24-hexadecimal digit string that identifies the desired snapshot.
     * 
     */
    @Import(name="snapshotId", required=true)
    private Output<String> snapshotId;

    /**
     * @return Unique 24-hexadecimal digit string that identifies the desired snapshot.
     * 
     */
    public Output<String> snapshotId() {
        return this.snapshotId;
    }

    private GetCloudBackupSnapshotDatabasesArgs() {}

    private GetCloudBackupSnapshotDatabasesArgs(GetCloudBackupSnapshotDatabasesArgs $) {
        this.clusterName = $.clusterName;
        this.projectId = $.projectId;
        this.snapshotId = $.snapshotId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetCloudBackupSnapshotDatabasesArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetCloudBackupSnapshotDatabasesArgs $;

        public Builder() {
            $ = new GetCloudBackupSnapshotDatabasesArgs();
        }

        public Builder(GetCloudBackupSnapshotDatabasesArgs defaults) {
            $ = new GetCloudBackupSnapshotDatabasesArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param clusterName Human-readable label that identifies the cluster.
         * 
         * @return builder
         * 
         */
        public Builder clusterName(Output<String> clusterName) {
            $.clusterName = clusterName;
            return this;
        }

        /**
         * @param clusterName Human-readable label that identifies the cluster.
         * 
         * @return builder
         * 
         */
        public Builder clusterName(String clusterName) {
            return clusterName(Output.of(clusterName));
        }

        /**
         * @param projectId Unique 24-hexadecimal digit string that identifies your project, also known as `groupId` in the official documentation.
         * 
         * @return builder
         * 
         */
        public Builder projectId(Output<String> projectId) {
            $.projectId = projectId;
            return this;
        }

        /**
         * @param projectId Unique 24-hexadecimal digit string that identifies your project, also known as `groupId` in the official documentation.
         * 
         * @return builder
         * 
         */
        public Builder projectId(String projectId) {
            return projectId(Output.of(projectId));
        }

        /**
         * @param snapshotId Unique 24-hexadecimal digit string that identifies the desired snapshot.
         * 
         * @return builder
         * 
         */
        public Builder snapshotId(Output<String> snapshotId) {
            $.snapshotId = snapshotId;
            return this;
        }

        /**
         * @param snapshotId Unique 24-hexadecimal digit string that identifies the desired snapshot.
         * 
         * @return builder
         * 
         */
        public Builder snapshotId(String snapshotId) {
            return snapshotId(Output.of(snapshotId));
        }

        public GetCloudBackupSnapshotDatabasesArgs build() {
            if ($.clusterName == null) {
                throw new MissingRequiredPropertyException("GetCloudBackupSnapshotDatabasesArgs", "clusterName");
            }
            if ($.projectId == null) {
                throw new MissingRequiredPropertyException("GetCloudBackupSnapshotDatabasesArgs", "projectId");
            }
            if ($.snapshotId == null) {
                throw new MissingRequiredPropertyException("GetCloudBackupSnapshotDatabasesArgs", "snapshotId");
            }
            return $;
        }
    }

}
