// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.mongodbatlas.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetLdapConfigurationPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetLdapConfigurationPlainArgs Empty = new GetLdapConfigurationPlainArgs();

    /**
     * Identifier for the Atlas project associated with the LDAP over TLS/SSL configuration.
     * 
     */
    @Import(name="projectId", required=true)
    private String projectId;

    /**
     * @return Identifier for the Atlas project associated with the LDAP over TLS/SSL configuration.
     * 
     */
    public String projectId() {
        return this.projectId;
    }

    private GetLdapConfigurationPlainArgs() {}

    private GetLdapConfigurationPlainArgs(GetLdapConfigurationPlainArgs $) {
        this.projectId = $.projectId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetLdapConfigurationPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetLdapConfigurationPlainArgs $;

        public Builder() {
            $ = new GetLdapConfigurationPlainArgs();
        }

        public Builder(GetLdapConfigurationPlainArgs defaults) {
            $ = new GetLdapConfigurationPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param projectId Identifier for the Atlas project associated with the LDAP over TLS/SSL configuration.
         * 
         * @return builder
         * 
         */
        public Builder projectId(String projectId) {
            $.projectId = projectId;
            return this;
        }

        public GetLdapConfigurationPlainArgs build() {
            if ($.projectId == null) {
                throw new MissingRequiredPropertyException("GetLdapConfigurationPlainArgs", "projectId");
            }
            return $;
        }
    }

}
