// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.mongodbatlas.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetStreamProcessorArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetStreamProcessorArgs Empty = new GetStreamProcessorArgs();

    /**
     * Label that identifies the stream processing workspace.
     * 
     * @deprecated
     * This parameter is deprecated. Please transition to workspace_name.
     * 
     */
    @Deprecated /* This parameter is deprecated. Please transition to workspace_name. */
    @Import(name="instanceName")
    private @Nullable Output<String> instanceName;

    /**
     * @return Label that identifies the stream processing workspace.
     * 
     * @deprecated
     * This parameter is deprecated. Please transition to workspace_name.
     * 
     */
    @Deprecated /* This parameter is deprecated. Please transition to workspace_name. */
    public Optional<Output<String>> instanceName() {
        return Optional.ofNullable(this.instanceName);
    }

    /**
     * Label that identifies the stream processor.
     * 
     */
    @Import(name="processorName", required=true)
    private Output<String> processorName;

    /**
     * @return Label that identifies the stream processor.
     * 
     */
    public Output<String> processorName() {
        return this.processorName;
    }

    /**
     * Unique 24-hexadecimal digit string that identifies your project, also known as `groupId` in the official documentation.
     * 
     */
    @Import(name="projectId", required=true)
    private Output<String> projectId;

    /**
     * @return Unique 24-hexadecimal digit string that identifies your project, also known as `groupId` in the official documentation.
     * 
     */
    public Output<String> projectId() {
        return this.projectId;
    }

    /**
     * Label that identifies the stream processing workspace. Conflicts with `instanceName`.
     * 
     */
    @Import(name="workspaceName")
    private @Nullable Output<String> workspaceName;

    /**
     * @return Label that identifies the stream processing workspace. Conflicts with `instanceName`.
     * 
     */
    public Optional<Output<String>> workspaceName() {
        return Optional.ofNullable(this.workspaceName);
    }

    private GetStreamProcessorArgs() {}

    private GetStreamProcessorArgs(GetStreamProcessorArgs $) {
        this.instanceName = $.instanceName;
        this.processorName = $.processorName;
        this.projectId = $.projectId;
        this.workspaceName = $.workspaceName;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetStreamProcessorArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetStreamProcessorArgs $;

        public Builder() {
            $ = new GetStreamProcessorArgs();
        }

        public Builder(GetStreamProcessorArgs defaults) {
            $ = new GetStreamProcessorArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param instanceName Label that identifies the stream processing workspace.
         * 
         * @return builder
         * 
         * @deprecated
         * This parameter is deprecated. Please transition to workspace_name.
         * 
         */
        @Deprecated /* This parameter is deprecated. Please transition to workspace_name. */
        public Builder instanceName(@Nullable Output<String> instanceName) {
            $.instanceName = instanceName;
            return this;
        }

        /**
         * @param instanceName Label that identifies the stream processing workspace.
         * 
         * @return builder
         * 
         * @deprecated
         * This parameter is deprecated. Please transition to workspace_name.
         * 
         */
        @Deprecated /* This parameter is deprecated. Please transition to workspace_name. */
        public Builder instanceName(String instanceName) {
            return instanceName(Output.of(instanceName));
        }

        /**
         * @param processorName Label that identifies the stream processor.
         * 
         * @return builder
         * 
         */
        public Builder processorName(Output<String> processorName) {
            $.processorName = processorName;
            return this;
        }

        /**
         * @param processorName Label that identifies the stream processor.
         * 
         * @return builder
         * 
         */
        public Builder processorName(String processorName) {
            return processorName(Output.of(processorName));
        }

        /**
         * @param projectId Unique 24-hexadecimal digit string that identifies your project, also known as `groupId` in the official documentation.
         * 
         * @return builder
         * 
         */
        public Builder projectId(Output<String> projectId) {
            $.projectId = projectId;
            return this;
        }

        /**
         * @param projectId Unique 24-hexadecimal digit string that identifies your project, also known as `groupId` in the official documentation.
         * 
         * @return builder
         * 
         */
        public Builder projectId(String projectId) {
            return projectId(Output.of(projectId));
        }

        /**
         * @param workspaceName Label that identifies the stream processing workspace. Conflicts with `instanceName`.
         * 
         * @return builder
         * 
         */
        public Builder workspaceName(@Nullable Output<String> workspaceName) {
            $.workspaceName = workspaceName;
            return this;
        }

        /**
         * @param workspaceName Label that identifies the stream processing workspace. Conflicts with `instanceName`.
         * 
         * @return builder
         * 
         */
        public Builder workspaceName(String workspaceName) {
            return workspaceName(Output.of(workspaceName));
        }

        public GetStreamProcessorArgs build() {
            if ($.processorName == null) {
                throw new MissingRequiredPropertyException("GetStreamProcessorArgs", "processorName");
            }
            if ($.projectId == null) {
                throw new MissingRequiredPropertyException("GetStreamProcessorArgs", "projectId");
            }
            return $;
        }
    }

}
