// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.mongodbatlas.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetSearchIndexesArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetSearchIndexesArgs Empty = new GetSearchIndexesArgs();

    /**
     * Name of the cluster containing the collection with one or more Atlas Search indexes.
     * 
     */
    @Import(name="clusterName", required=true)
    private Output<String> clusterName;

    /**
     * @return Name of the cluster containing the collection with one or more Atlas Search indexes.
     * 
     */
    public Output<String> clusterName() {
        return this.clusterName;
    }

    /**
     * Name of the collection with one or more Atlas Search indexes.
     * 
     */
    @Import(name="collectionName", required=true)
    private Output<String> collectionName;

    /**
     * @return Name of the collection with one or more Atlas Search indexes.
     * 
     */
    public Output<String> collectionName() {
        return this.collectionName;
    }

    /**
     * (Required) Name of the database the collection is in.
     * 
     */
    @Import(name="database", required=true)
    private Output<String> database;

    /**
     * @return (Required) Name of the database the collection is in.
     * 
     */
    public Output<String> database() {
        return this.database;
    }

    /**
     * Unique identifier for the [project](https://docs.atlas.mongodb.com/organizations-projects/#std-label-projects) that contains the specified cluster.
     * 
     */
    @Import(name="projectId", required=true)
    private Output<String> projectId;

    /**
     * @return Unique identifier for the [project](https://docs.atlas.mongodb.com/organizations-projects/#std-label-projects) that contains the specified cluster.
     * 
     */
    public Output<String> projectId() {
        return this.projectId;
    }

    private GetSearchIndexesArgs() {}

    private GetSearchIndexesArgs(GetSearchIndexesArgs $) {
        this.clusterName = $.clusterName;
        this.collectionName = $.collectionName;
        this.database = $.database;
        this.projectId = $.projectId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetSearchIndexesArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetSearchIndexesArgs $;

        public Builder() {
            $ = new GetSearchIndexesArgs();
        }

        public Builder(GetSearchIndexesArgs defaults) {
            $ = new GetSearchIndexesArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param clusterName Name of the cluster containing the collection with one or more Atlas Search indexes.
         * 
         * @return builder
         * 
         */
        public Builder clusterName(Output<String> clusterName) {
            $.clusterName = clusterName;
            return this;
        }

        /**
         * @param clusterName Name of the cluster containing the collection with one or more Atlas Search indexes.
         * 
         * @return builder
         * 
         */
        public Builder clusterName(String clusterName) {
            return clusterName(Output.of(clusterName));
        }

        /**
         * @param collectionName Name of the collection with one or more Atlas Search indexes.
         * 
         * @return builder
         * 
         */
        public Builder collectionName(Output<String> collectionName) {
            $.collectionName = collectionName;
            return this;
        }

        /**
         * @param collectionName Name of the collection with one or more Atlas Search indexes.
         * 
         * @return builder
         * 
         */
        public Builder collectionName(String collectionName) {
            return collectionName(Output.of(collectionName));
        }

        /**
         * @param database (Required) Name of the database the collection is in.
         * 
         * @return builder
         * 
         */
        public Builder database(Output<String> database) {
            $.database = database;
            return this;
        }

        /**
         * @param database (Required) Name of the database the collection is in.
         * 
         * @return builder
         * 
         */
        public Builder database(String database) {
            return database(Output.of(database));
        }

        /**
         * @param projectId Unique identifier for the [project](https://docs.atlas.mongodb.com/organizations-projects/#std-label-projects) that contains the specified cluster.
         * 
         * @return builder
         * 
         */
        public Builder projectId(Output<String> projectId) {
            $.projectId = projectId;
            return this;
        }

        /**
         * @param projectId Unique identifier for the [project](https://docs.atlas.mongodb.com/organizations-projects/#std-label-projects) that contains the specified cluster.
         * 
         * @return builder
         * 
         */
        public Builder projectId(String projectId) {
            return projectId(Output.of(projectId));
        }

        public GetSearchIndexesArgs build() {
            if ($.clusterName == null) {
                throw new MissingRequiredPropertyException("GetSearchIndexesArgs", "clusterName");
            }
            if ($.collectionName == null) {
                throw new MissingRequiredPropertyException("GetSearchIndexesArgs", "collectionName");
            }
            if ($.database == null) {
                throw new MissingRequiredPropertyException("GetSearchIndexesArgs", "database");
            }
            if ($.projectId == null) {
                throw new MissingRequiredPropertyException("GetSearchIndexesArgs", "projectId");
            }
            return $;
        }
    }

}
