// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.mongodbatlas.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.mongodbatlas.inputs.OrgLogIntegrationOtelSuppliedHeaderArgs;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class OrgLogIntegrationState extends com.pulumi.resources.ResourceArgs {

    public static final OrgLogIntegrationState Empty = new OrgLogIntegrationState();

    /**
     * Unique 24-character hexadecimal digit string that identifies the log integration configuration.
     * 
     */
    @Import(name="integrationId")
    private @Nullable Output<String> integrationId;

    /**
     * @return Unique 24-character hexadecimal digit string that identifies the log integration configuration.
     * 
     */
    public Optional<Output<String>> integrationId() {
        return Optional.ofNullable(this.integrationId);
    }

    /**
     * Array of log types exported by this integration.
     * 
     */
    @Import(name="logTypes")
    private @Nullable Output<List<String>> logTypes;

    /**
     * @return Array of log types exported by this integration.
     * 
     */
    public Optional<Output<List<String>>> logTypes() {
        return Optional.ofNullable(this.logTypes);
    }

    /**
     * Unique 24-hexadecimal digit string that identifies the organization that contains your projects.
     * 
     */
    @Import(name="orgId")
    private @Nullable Output<String> orgId;

    /**
     * @return Unique 24-hexadecimal digit string that identifies the organization that contains your projects.
     * 
     */
    public Optional<Output<String>> orgId() {
        return Optional.ofNullable(this.orgId);
    }

    /**
     * OpenTelemetry collector endpoint URL. Must be HTTPS and not exceed 2048 characters.
     * 
     */
    @Import(name="otelEndpoint")
    private @Nullable Output<String> otelEndpoint;

    /**
     * @return OpenTelemetry collector endpoint URL. Must be HTTPS and not exceed 2048 characters.
     * 
     */
    public Optional<Output<String>> otelEndpoint() {
        return Optional.ofNullable(this.otelEndpoint);
    }

    /**
     * HTTP headers for authentication and configuration. Maximum 10 headers, total size limit 2KB.
     * 
     */
    @Import(name="otelSuppliedHeaders")
    private @Nullable Output<List<OrgLogIntegrationOtelSuppliedHeaderArgs>> otelSuppliedHeaders;

    /**
     * @return HTTP headers for authentication and configuration. Maximum 10 headers, total size limit 2KB.
     * 
     */
    public Optional<Output<List<OrgLogIntegrationOtelSuppliedHeaderArgs>>> otelSuppliedHeaders() {
        return Optional.ofNullable(this.otelSuppliedHeaders);
    }

    /**
     * Human-readable label that identifies the service to which you want to integrate with Atlas. The value must match the log integration type. This value cannot be modified after the integration is created.
     * 
     */
    @Import(name="type")
    private @Nullable Output<String> type;

    /**
     * @return Human-readable label that identifies the service to which you want to integrate with Atlas. The value must match the log integration type. This value cannot be modified after the integration is created.
     * 
     */
    public Optional<Output<String>> type() {
        return Optional.ofNullable(this.type);
    }

    private OrgLogIntegrationState() {}

    private OrgLogIntegrationState(OrgLogIntegrationState $) {
        this.integrationId = $.integrationId;
        this.logTypes = $.logTypes;
        this.orgId = $.orgId;
        this.otelEndpoint = $.otelEndpoint;
        this.otelSuppliedHeaders = $.otelSuppliedHeaders;
        this.type = $.type;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(OrgLogIntegrationState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private OrgLogIntegrationState $;

        public Builder() {
            $ = new OrgLogIntegrationState();
        }

        public Builder(OrgLogIntegrationState defaults) {
            $ = new OrgLogIntegrationState(Objects.requireNonNull(defaults));
        }

        /**
         * @param integrationId Unique 24-character hexadecimal digit string that identifies the log integration configuration.
         * 
         * @return builder
         * 
         */
        public Builder integrationId(@Nullable Output<String> integrationId) {
            $.integrationId = integrationId;
            return this;
        }

        /**
         * @param integrationId Unique 24-character hexadecimal digit string that identifies the log integration configuration.
         * 
         * @return builder
         * 
         */
        public Builder integrationId(String integrationId) {
            return integrationId(Output.of(integrationId));
        }

        /**
         * @param logTypes Array of log types exported by this integration.
         * 
         * @return builder
         * 
         */
        public Builder logTypes(@Nullable Output<List<String>> logTypes) {
            $.logTypes = logTypes;
            return this;
        }

        /**
         * @param logTypes Array of log types exported by this integration.
         * 
         * @return builder
         * 
         */
        public Builder logTypes(List<String> logTypes) {
            return logTypes(Output.of(logTypes));
        }

        /**
         * @param logTypes Array of log types exported by this integration.
         * 
         * @return builder
         * 
         */
        public Builder logTypes(String... logTypes) {
            return logTypes(List.of(logTypes));
        }

        /**
         * @param orgId Unique 24-hexadecimal digit string that identifies the organization that contains your projects.
         * 
         * @return builder
         * 
         */
        public Builder orgId(@Nullable Output<String> orgId) {
            $.orgId = orgId;
            return this;
        }

        /**
         * @param orgId Unique 24-hexadecimal digit string that identifies the organization that contains your projects.
         * 
         * @return builder
         * 
         */
        public Builder orgId(String orgId) {
            return orgId(Output.of(orgId));
        }

        /**
         * @param otelEndpoint OpenTelemetry collector endpoint URL. Must be HTTPS and not exceed 2048 characters.
         * 
         * @return builder
         * 
         */
        public Builder otelEndpoint(@Nullable Output<String> otelEndpoint) {
            $.otelEndpoint = otelEndpoint;
            return this;
        }

        /**
         * @param otelEndpoint OpenTelemetry collector endpoint URL. Must be HTTPS and not exceed 2048 characters.
         * 
         * @return builder
         * 
         */
        public Builder otelEndpoint(String otelEndpoint) {
            return otelEndpoint(Output.of(otelEndpoint));
        }

        /**
         * @param otelSuppliedHeaders HTTP headers for authentication and configuration. Maximum 10 headers, total size limit 2KB.
         * 
         * @return builder
         * 
         */
        public Builder otelSuppliedHeaders(@Nullable Output<List<OrgLogIntegrationOtelSuppliedHeaderArgs>> otelSuppliedHeaders) {
            $.otelSuppliedHeaders = otelSuppliedHeaders;
            return this;
        }

        /**
         * @param otelSuppliedHeaders HTTP headers for authentication and configuration. Maximum 10 headers, total size limit 2KB.
         * 
         * @return builder
         * 
         */
        public Builder otelSuppliedHeaders(List<OrgLogIntegrationOtelSuppliedHeaderArgs> otelSuppliedHeaders) {
            return otelSuppliedHeaders(Output.of(otelSuppliedHeaders));
        }

        /**
         * @param otelSuppliedHeaders HTTP headers for authentication and configuration. Maximum 10 headers, total size limit 2KB.
         * 
         * @return builder
         * 
         */
        public Builder otelSuppliedHeaders(OrgLogIntegrationOtelSuppliedHeaderArgs... otelSuppliedHeaders) {
            return otelSuppliedHeaders(List.of(otelSuppliedHeaders));
        }

        /**
         * @param type Human-readable label that identifies the service to which you want to integrate with Atlas. The value must match the log integration type. This value cannot be modified after the integration is created.
         * 
         * @return builder
         * 
         */
        public Builder type(@Nullable Output<String> type) {
            $.type = type;
            return this;
        }

        /**
         * @param type Human-readable label that identifies the service to which you want to integrate with Atlas. The value must match the log integration type. This value cannot be modified after the integration is created.
         * 
         * @return builder
         * 
         */
        public Builder type(String type) {
            return type(Output.of(type));
        }

        public OrgLogIntegrationState build() {
            return $;
        }
    }

}
