# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['OrgLogIntegrationArgs', 'OrgLogIntegration']

@pulumi.input_type
class OrgLogIntegrationArgs:
    def __init__(__self__, *,
                 log_types: pulumi.Input[Sequence[pulumi.Input[_builtins.str]]],
                 org_id: pulumi.Input[_builtins.str],
                 type: pulumi.Input[_builtins.str],
                 otel_endpoint: pulumi.Input[Optional[_builtins.str]] = None,
                 otel_supplied_headers: pulumi.Input[Optional[Sequence[pulumi.Input['OrgLogIntegrationOtelSuppliedHeaderArgs']]]] = None):
        """
        The set of arguments for constructing a OrgLogIntegration resource.

        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] log_types: Array of log types exported by this integration.
        :param pulumi.Input[_builtins.str] org_id: Unique 24-hexadecimal digit string that identifies the organization that contains your projects.
        :param pulumi.Input[_builtins.str] type: Human-readable label that identifies the service to which you want to integrate with Atlas. The value must match the log integration type. This value cannot be modified after the integration is created.
        :param pulumi.Input[_builtins.str] otel_endpoint: OpenTelemetry collector endpoint URL. Must be HTTPS and not exceed 2048 characters.
        :param pulumi.Input[Sequence[pulumi.Input['OrgLogIntegrationOtelSuppliedHeaderArgs']]] otel_supplied_headers: HTTP headers for authentication and configuration. Maximum 10 headers, total size limit 2KB.
        """
        pulumi.set(__self__, "log_types", log_types)
        pulumi.set(__self__, "org_id", org_id)
        pulumi.set(__self__, "type", type)
        if otel_endpoint is not None:
            pulumi.set(__self__, "otel_endpoint", otel_endpoint)
        if otel_supplied_headers is not None:
            pulumi.set(__self__, "otel_supplied_headers", otel_supplied_headers)

    @_builtins.property
    @pulumi.getter(name="logTypes")
    def log_types(self) -> pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]:
        """
        Array of log types exported by this integration.
        """
        return pulumi.get(self, "log_types")

    @log_types.setter
    def log_types(self, value: pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]):
        pulumi.set(self, "log_types", value)

    @_builtins.property
    @pulumi.getter(name="orgId")
    def org_id(self) -> pulumi.Input[_builtins.str]:
        """
        Unique 24-hexadecimal digit string that identifies the organization that contains your projects.
        """
        return pulumi.get(self, "org_id")

    @org_id.setter
    def org_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "org_id", value)

    @_builtins.property
    @pulumi.getter
    def type(self) -> pulumi.Input[_builtins.str]:
        """
        Human-readable label that identifies the service to which you want to integrate with Atlas. The value must match the log integration type. This value cannot be modified after the integration is created.
        """
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "type", value)

    @_builtins.property
    @pulumi.getter(name="otelEndpoint")
    def otel_endpoint(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        OpenTelemetry collector endpoint URL. Must be HTTPS and not exceed 2048 characters.
        """
        return pulumi.get(self, "otel_endpoint")

    @otel_endpoint.setter
    def otel_endpoint(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "otel_endpoint", value)

    @_builtins.property
    @pulumi.getter(name="otelSuppliedHeaders")
    def otel_supplied_headers(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['OrgLogIntegrationOtelSuppliedHeaderArgs']]]]:
        """
        HTTP headers for authentication and configuration. Maximum 10 headers, total size limit 2KB.
        """
        return pulumi.get(self, "otel_supplied_headers")

    @otel_supplied_headers.setter
    def otel_supplied_headers(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['OrgLogIntegrationOtelSuppliedHeaderArgs']]]]):
        pulumi.set(self, "otel_supplied_headers", value)


@pulumi.input_type
class _OrgLogIntegrationState:
    def __init__(__self__, *,
                 integration_id: pulumi.Input[Optional[_builtins.str]] = None,
                 log_types: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 org_id: pulumi.Input[Optional[_builtins.str]] = None,
                 otel_endpoint: pulumi.Input[Optional[_builtins.str]] = None,
                 otel_supplied_headers: pulumi.Input[Optional[Sequence[pulumi.Input['OrgLogIntegrationOtelSuppliedHeaderArgs']]]] = None,
                 type: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering OrgLogIntegration resources.

        :param pulumi.Input[_builtins.str] integration_id: Unique 24-character hexadecimal digit string that identifies the log integration configuration.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] log_types: Array of log types exported by this integration.
        :param pulumi.Input[_builtins.str] org_id: Unique 24-hexadecimal digit string that identifies the organization that contains your projects.
        :param pulumi.Input[_builtins.str] otel_endpoint: OpenTelemetry collector endpoint URL. Must be HTTPS and not exceed 2048 characters.
        :param pulumi.Input[Sequence[pulumi.Input['OrgLogIntegrationOtelSuppliedHeaderArgs']]] otel_supplied_headers: HTTP headers for authentication and configuration. Maximum 10 headers, total size limit 2KB.
        :param pulumi.Input[_builtins.str] type: Human-readable label that identifies the service to which you want to integrate with Atlas. The value must match the log integration type. This value cannot be modified after the integration is created.
        """
        if integration_id is not None:
            pulumi.set(__self__, "integration_id", integration_id)
        if log_types is not None:
            pulumi.set(__self__, "log_types", log_types)
        if org_id is not None:
            pulumi.set(__self__, "org_id", org_id)
        if otel_endpoint is not None:
            pulumi.set(__self__, "otel_endpoint", otel_endpoint)
        if otel_supplied_headers is not None:
            pulumi.set(__self__, "otel_supplied_headers", otel_supplied_headers)
        if type is not None:
            pulumi.set(__self__, "type", type)

    @_builtins.property
    @pulumi.getter(name="integrationId")
    def integration_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Unique 24-character hexadecimal digit string that identifies the log integration configuration.
        """
        return pulumi.get(self, "integration_id")

    @integration_id.setter
    def integration_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "integration_id", value)

    @_builtins.property
    @pulumi.getter(name="logTypes")
    def log_types(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Array of log types exported by this integration.
        """
        return pulumi.get(self, "log_types")

    @log_types.setter
    def log_types(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "log_types", value)

    @_builtins.property
    @pulumi.getter(name="orgId")
    def org_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Unique 24-hexadecimal digit string that identifies the organization that contains your projects.
        """
        return pulumi.get(self, "org_id")

    @org_id.setter
    def org_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "org_id", value)

    @_builtins.property
    @pulumi.getter(name="otelEndpoint")
    def otel_endpoint(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        OpenTelemetry collector endpoint URL. Must be HTTPS and not exceed 2048 characters.
        """
        return pulumi.get(self, "otel_endpoint")

    @otel_endpoint.setter
    def otel_endpoint(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "otel_endpoint", value)

    @_builtins.property
    @pulumi.getter(name="otelSuppliedHeaders")
    def otel_supplied_headers(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['OrgLogIntegrationOtelSuppliedHeaderArgs']]]]:
        """
        HTTP headers for authentication and configuration. Maximum 10 headers, total size limit 2KB.
        """
        return pulumi.get(self, "otel_supplied_headers")

    @otel_supplied_headers.setter
    def otel_supplied_headers(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['OrgLogIntegrationOtelSuppliedHeaderArgs']]]]):
        pulumi.set(self, "otel_supplied_headers", value)

    @_builtins.property
    @pulumi.getter
    def type(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Human-readable label that identifies the service to which you want to integrate with Atlas. The value must match the log integration type. This value cannot be modified after the integration is created.
        """
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "type", value)


@pulumi.type_token("mongodbatlas:index/orgLogIntegration:OrgLogIntegration")
class OrgLogIntegration(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 log_types: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 org_id: pulumi.Input[Optional[_builtins.str]] = None,
                 otel_endpoint: pulumi.Input[Optional[_builtins.str]] = None,
                 otel_supplied_headers: pulumi.Input[Optional[Sequence[pulumi.Input[Union['OrgLogIntegrationOtelSuppliedHeaderArgs', 'OrgLogIntegrationOtelSuppliedHeaderArgsDict', 'outputs.OrgLogIntegrationOtelSuppliedHeader']]]]] = None,
                 type: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        `OrgLogIntegration` provides a resource for managing log integration configurations at the organization level. This resource allows you to export organization events to an external service. Currently, OpenTelemetry is the only supported integration type.

        To use this resource, the requesting Service Account or API Key must have the Organization Owner role.

        ## Example Usage

        ### S

        ### OpenTelemetry

        ```python
        import pulumi
        import pulumi_mongodbatlas as mongodbatlas

        example = mongodbatlas.OrgLogIntegration("example",
            org_id=atlas_org_id,
            type="OTEL_LOG_EXPORT",
            log_types=["EVENTS"],
            otel_endpoint=otel_endpoint,
            otel_supplied_headers=otel_supplied_headers)
        ```

        ## Import

        Organization Log Integration resource can be imported using the organization ID and log integration ID, separated by a slash, e.g.

        > **NOTE:** After importing a `OrgLogIntegration` resource with a configuration that sets non-empty header values, the first `pulumi preview` shows a diff on `otel_supplied_headers` because the Atlas API redacts these values in GET responses. The diff is expected and resolves after running `pulumi up` once.

        For more information see: [MongoDB Atlas API - Organization Log Integration](https://www.mongodb.com/docs/api/doc/atlas-admin-api-v2/group/endpoint-push-based-log-export) Documentation.


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] log_types: Array of log types exported by this integration.
        :param pulumi.Input[_builtins.str] org_id: Unique 24-hexadecimal digit string that identifies the organization that contains your projects.
        :param pulumi.Input[_builtins.str] otel_endpoint: OpenTelemetry collector endpoint URL. Must be HTTPS and not exceed 2048 characters.
        :param pulumi.Input[Sequence[pulumi.Input[Union['OrgLogIntegrationOtelSuppliedHeaderArgs', 'OrgLogIntegrationOtelSuppliedHeaderArgsDict', 'outputs.OrgLogIntegrationOtelSuppliedHeader']]]] otel_supplied_headers: HTTP headers for authentication and configuration. Maximum 10 headers, total size limit 2KB.
        :param pulumi.Input[_builtins.str] type: Human-readable label that identifies the service to which you want to integrate with Atlas. The value must match the log integration type. This value cannot be modified after the integration is created.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: OrgLogIntegrationArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        `OrgLogIntegration` provides a resource for managing log integration configurations at the organization level. This resource allows you to export organization events to an external service. Currently, OpenTelemetry is the only supported integration type.

        To use this resource, the requesting Service Account or API Key must have the Organization Owner role.

        ## Example Usage

        ### S

        ### OpenTelemetry

        ```python
        import pulumi
        import pulumi_mongodbatlas as mongodbatlas

        example = mongodbatlas.OrgLogIntegration("example",
            org_id=atlas_org_id,
            type="OTEL_LOG_EXPORT",
            log_types=["EVENTS"],
            otel_endpoint=otel_endpoint,
            otel_supplied_headers=otel_supplied_headers)
        ```

        ## Import

        Organization Log Integration resource can be imported using the organization ID and log integration ID, separated by a slash, e.g.

        > **NOTE:** After importing a `OrgLogIntegration` resource with a configuration that sets non-empty header values, the first `pulumi preview` shows a diff on `otel_supplied_headers` because the Atlas API redacts these values in GET responses. The diff is expected and resolves after running `pulumi up` once.

        For more information see: [MongoDB Atlas API - Organization Log Integration](https://www.mongodb.com/docs/api/doc/atlas-admin-api-v2/group/endpoint-push-based-log-export) Documentation.


        :param str resource_name: The name of the resource.
        :param OrgLogIntegrationArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(OrgLogIntegrationArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 log_types: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 org_id: pulumi.Input[Optional[_builtins.str]] = None,
                 otel_endpoint: pulumi.Input[Optional[_builtins.str]] = None,
                 otel_supplied_headers: pulumi.Input[Optional[Sequence[pulumi.Input[Union['OrgLogIntegrationOtelSuppliedHeaderArgs', 'OrgLogIntegrationOtelSuppliedHeaderArgsDict', 'outputs.OrgLogIntegrationOtelSuppliedHeader']]]]] = None,
                 type: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = OrgLogIntegrationArgs.__new__(OrgLogIntegrationArgs)

            if log_types is None and not opts.urn:
                raise TypeError("Missing required property 'log_types'")
            __props__.__dict__["log_types"] = log_types
            if org_id is None and not opts.urn:
                raise TypeError("Missing required property 'org_id'")
            __props__.__dict__["org_id"] = org_id
            __props__.__dict__["otel_endpoint"] = otel_endpoint
            __props__.__dict__["otel_supplied_headers"] = None if otel_supplied_headers is None else pulumi.Output.secret(otel_supplied_headers)
            if type is None and not opts.urn:
                raise TypeError("Missing required property 'type'")
            __props__.__dict__["type"] = type
            __props__.__dict__["integration_id"] = None
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["otelSuppliedHeaders"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(OrgLogIntegration, __self__).__init__(
            'mongodbatlas:index/orgLogIntegration:OrgLogIntegration',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            integration_id: pulumi.Input[Optional[_builtins.str]] = None,
            log_types: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
            org_id: pulumi.Input[Optional[_builtins.str]] = None,
            otel_endpoint: pulumi.Input[Optional[_builtins.str]] = None,
            otel_supplied_headers: pulumi.Input[Optional[Sequence[pulumi.Input[Union['OrgLogIntegrationOtelSuppliedHeaderArgs', 'OrgLogIntegrationOtelSuppliedHeaderArgsDict', 'outputs.OrgLogIntegrationOtelSuppliedHeader']]]]] = None,
            type: pulumi.Input[Optional[_builtins.str]] = None) -> 'OrgLogIntegration':
        """
        Get an existing OrgLogIntegration resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] integration_id: Unique 24-character hexadecimal digit string that identifies the log integration configuration.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] log_types: Array of log types exported by this integration.
        :param pulumi.Input[_builtins.str] org_id: Unique 24-hexadecimal digit string that identifies the organization that contains your projects.
        :param pulumi.Input[_builtins.str] otel_endpoint: OpenTelemetry collector endpoint URL. Must be HTTPS and not exceed 2048 characters.
        :param pulumi.Input[Sequence[pulumi.Input[Union['OrgLogIntegrationOtelSuppliedHeaderArgs', 'OrgLogIntegrationOtelSuppliedHeaderArgsDict', 'outputs.OrgLogIntegrationOtelSuppliedHeader']]]] otel_supplied_headers: HTTP headers for authentication and configuration. Maximum 10 headers, total size limit 2KB.
        :param pulumi.Input[_builtins.str] type: Human-readable label that identifies the service to which you want to integrate with Atlas. The value must match the log integration type. This value cannot be modified after the integration is created.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _OrgLogIntegrationState.__new__(_OrgLogIntegrationState)

        __props__.__dict__["integration_id"] = integration_id
        __props__.__dict__["log_types"] = log_types
        __props__.__dict__["org_id"] = org_id
        __props__.__dict__["otel_endpoint"] = otel_endpoint
        __props__.__dict__["otel_supplied_headers"] = otel_supplied_headers
        __props__.__dict__["type"] = type
        return OrgLogIntegration(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="integrationId")
    def integration_id(self) -> pulumi.Output[_builtins.str]:
        """
        Unique 24-character hexadecimal digit string that identifies the log integration configuration.
        """
        return pulumi.get(self, "integration_id")

    @_builtins.property
    @pulumi.getter(name="logTypes")
    def log_types(self) -> pulumi.Output[Sequence[_builtins.str]]:
        """
        Array of log types exported by this integration.
        """
        return pulumi.get(self, "log_types")

    @_builtins.property
    @pulumi.getter(name="orgId")
    def org_id(self) -> pulumi.Output[_builtins.str]:
        """
        Unique 24-hexadecimal digit string that identifies the organization that contains your projects.
        """
        return pulumi.get(self, "org_id")

    @_builtins.property
    @pulumi.getter(name="otelEndpoint")
    def otel_endpoint(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        OpenTelemetry collector endpoint URL. Must be HTTPS and not exceed 2048 characters.
        """
        return pulumi.get(self, "otel_endpoint")

    @_builtins.property
    @pulumi.getter(name="otelSuppliedHeaders")
    def otel_supplied_headers(self) -> pulumi.Output[Optional[Sequence['outputs.OrgLogIntegrationOtelSuppliedHeader']]]:
        """
        HTTP headers for authentication and configuration. Maximum 10 headers, total size limit 2KB.
        """
        return pulumi.get(self, "otel_supplied_headers")

    @_builtins.property
    @pulumi.getter
    def type(self) -> pulumi.Output[_builtins.str]:
        """
        Human-readable label that identifies the service to which you want to integrate with Atlas. The value must match the log integration type. This value cannot be modified after the integration is created.
        """
        return pulumi.get(self, "type")

