// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Mongodbatlas.Outputs
{

    [OutputType]
    public sealed class GetStreamProcessorOptionsResult
    {
        /// <summary>
        /// Dead letter queue for the stream processor. Refer to the [MongoDB Atlas Docs](https://www.mongodb.com/docs/atlas/reference/glossary/#std-term-dead-letter-queue) for more information.
        /// </summary>
        public readonly Outputs.GetStreamProcessorOptionsDlqResult Dlq;

        [OutputConstructor]
        private GetStreamProcessorOptionsResult(Outputs.GetStreamProcessorOptionsDlqResult dlq)
        {
            Dlq = dlq;
        }
    }
}
