// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Mongodbatlas.Outputs
{

    [OutputType]
    public sealed class ProjectLimit
    {
        public readonly int? CurrentUsage;
        public readonly int? DefaultLimit;
        public readonly int? MaximumLimit;
        /// <summary>
        /// Human-readable label that identifies this project limit. See [Project Limit Documentation](https://www.mongodb.com/docs/atlas/reference/api-resources-spec/#tag/Projects/operation/setProjectLimit) under `limitName` parameter to find all the limits that can be defined.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Amount to set the limit to. Use the [Project Limit Documentation](https://www.mongodb.com/docs/atlas/reference/api-resources-spec/#tag/Projects/operation/setProjectLimit) under `limitName` parameter to verify the override limits.
        /// </summary>
        public readonly int Value;

        [OutputConstructor]
        private ProjectLimit(
            int? currentUsage,

            int? defaultLimit,

            int? maximumLimit,

            string name,

            int value)
        {
            CurrentUsage = currentUsage;
            DefaultLimit = defaultLimit;
            MaximumLimit = maximumLimit;
            Name = name;
            Value = value;
        }
    }
}
