// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Mongodbatlas.Outputs
{

    [OutputType]
    public sealed class ProjectTeam
    {
        /// <summary>
        /// Each string in the array represents a project role you want to assign to the team. Every user associated with the team inherits these roles. You must specify an array even if you are only associating a single role with the team.
        /// The following are valid roles:
        /// </summary>
        public readonly ImmutableArray<string> RoleNames;
        /// <summary>
        /// The unique identifier of the team you want to associate with the project. The team and project must share the same parent organization.
        /// </summary>
        public readonly string TeamId;

        [OutputConstructor]
        private ProjectTeam(
            ImmutableArray<string> roleNames,

            string teamId)
        {
            RoleNames = roleNames;
            TeamId = teamId;
        }
    }
}
