// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Mongodbatlas.Outputs
{

    [OutputType]
    public sealed class SearchIndexTypeSet
    {
        /// <summary>
        /// Name of the type set.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// JSON array describing the types.
        /// </summary>
        public readonly string? Types;

        [OutputConstructor]
        private SearchIndexTypeSet(
            string name,

            string? types)
        {
            Name = name;
            Types = types;
        }
    }
}
