// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.mongodbatlas;

import com.pulumi.core.internal.Codegen;
import java.lang.String;
import java.util.Optional;

public final class Config {

    private static final com.pulumi.Config config = com.pulumi.Config.of("mongodbatlas");
/**
 * MongoDB Atlas Base URL
 * 
 */
    public Optional<String> baseUrl() {
        return Codegen.stringProp("baseUrl").config(config).get();
    }
/**
 * MongoDB Atlas Programmatic Private Key
 * 
 */
    public Optional<String> privateKey() {
        return Codegen.stringProp("privateKey").config(config).get();
    }
/**
 * MongoDB Atlas Programmatic Public Key
 * 
 */
    public Optional<String> publicKey() {
        return Codegen.stringProp("publicKey").config(config).get();
    }
/**
 * MongoDB Realm Base URL
 * 
 */
    public Optional<String> realmBaseUrl() {
        return Codegen.stringProp("realmBaseUrl").config(config).get();
    }
}
