// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.mongodbatlas.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetApiKeyProjectAssignmentResult {
    /**
     * @return Unique 24-hexadecimal digit string that identifies this organization API key that you want to assign to one project.
     * 
     */
    private String apiKeyId;
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private String id;
    /**
     * @return Unique 24-hexadecimal digit string that identifies your project. Use the /groups endpoint to retrieve all projects to which the authenticated user has access.
     * 
     */
    private String projectId;
    private List<String> roles;

    private GetApiKeyProjectAssignmentResult() {}
    /**
     * @return Unique 24-hexadecimal digit string that identifies this organization API key that you want to assign to one project.
     * 
     */
    public String apiKeyId() {
        return this.apiKeyId;
    }
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return Unique 24-hexadecimal digit string that identifies your project. Use the /groups endpoint to retrieve all projects to which the authenticated user has access.
     * 
     */
    public String projectId() {
        return this.projectId;
    }
    public List<String> roles() {
        return this.roles;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetApiKeyProjectAssignmentResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String apiKeyId;
        private String id;
        private String projectId;
        private List<String> roles;
        public Builder() {}
        public Builder(GetApiKeyProjectAssignmentResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.apiKeyId = defaults.apiKeyId;
    	      this.id = defaults.id;
    	      this.projectId = defaults.projectId;
    	      this.roles = defaults.roles;
        }

        @CustomType.Setter
        public Builder apiKeyId(String apiKeyId) {
            if (apiKeyId == null) {
              throw new MissingRequiredPropertyException("GetApiKeyProjectAssignmentResult", "apiKeyId");
            }
            this.apiKeyId = apiKeyId;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetApiKeyProjectAssignmentResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder projectId(String projectId) {
            if (projectId == null) {
              throw new MissingRequiredPropertyException("GetApiKeyProjectAssignmentResult", "projectId");
            }
            this.projectId = projectId;
            return this;
        }
        @CustomType.Setter
        public Builder roles(List<String> roles) {
            if (roles == null) {
              throw new MissingRequiredPropertyException("GetApiKeyProjectAssignmentResult", "roles");
            }
            this.roles = roles;
            return this;
        }
        public Builder roles(String... roles) {
            return roles(List.of(roles));
        }
        public GetApiKeyProjectAssignmentResult build() {
            final var _resultValue = new GetApiKeyProjectAssignmentResult();
            _resultValue.apiKeyId = apiKeyId;
            _resultValue.id = id;
            _resultValue.projectId = projectId;
            _resultValue.roles = roles;
            return _resultValue;
        }
    }
}
