// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.mongodbatlas.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetAccessListApiKeyResult {
    private Integer accessCount;
    private String apiKeyId;
    private String cidrBlock;
    private String created;
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private String id;
    private String ipAddress;
    private String lastUsed;
    private String lastUsedAddress;
    private String orgId;

    private GetAccessListApiKeyResult() {}
    public Integer accessCount() {
        return this.accessCount;
    }
    public String apiKeyId() {
        return this.apiKeyId;
    }
    public String cidrBlock() {
        return this.cidrBlock;
    }
    public String created() {
        return this.created;
    }
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }
    public String ipAddress() {
        return this.ipAddress;
    }
    public String lastUsed() {
        return this.lastUsed;
    }
    public String lastUsedAddress() {
        return this.lastUsedAddress;
    }
    public String orgId() {
        return this.orgId;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetAccessListApiKeyResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Integer accessCount;
        private String apiKeyId;
        private String cidrBlock;
        private String created;
        private String id;
        private String ipAddress;
        private String lastUsed;
        private String lastUsedAddress;
        private String orgId;
        public Builder() {}
        public Builder(GetAccessListApiKeyResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.accessCount = defaults.accessCount;
    	      this.apiKeyId = defaults.apiKeyId;
    	      this.cidrBlock = defaults.cidrBlock;
    	      this.created = defaults.created;
    	      this.id = defaults.id;
    	      this.ipAddress = defaults.ipAddress;
    	      this.lastUsed = defaults.lastUsed;
    	      this.lastUsedAddress = defaults.lastUsedAddress;
    	      this.orgId = defaults.orgId;
        }

        @CustomType.Setter
        public Builder accessCount(Integer accessCount) {
            this.accessCount = Objects.requireNonNull(accessCount);
            return this;
        }
        @CustomType.Setter
        public Builder apiKeyId(String apiKeyId) {
            this.apiKeyId = Objects.requireNonNull(apiKeyId);
            return this;
        }
        @CustomType.Setter
        public Builder cidrBlock(String cidrBlock) {
            this.cidrBlock = Objects.requireNonNull(cidrBlock);
            return this;
        }
        @CustomType.Setter
        public Builder created(String created) {
            this.created = Objects.requireNonNull(created);
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            this.id = Objects.requireNonNull(id);
            return this;
        }
        @CustomType.Setter
        public Builder ipAddress(String ipAddress) {
            this.ipAddress = Objects.requireNonNull(ipAddress);
            return this;
        }
        @CustomType.Setter
        public Builder lastUsed(String lastUsed) {
            this.lastUsed = Objects.requireNonNull(lastUsed);
            return this;
        }
        @CustomType.Setter
        public Builder lastUsedAddress(String lastUsedAddress) {
            this.lastUsedAddress = Objects.requireNonNull(lastUsedAddress);
            return this;
        }
        @CustomType.Setter
        public Builder orgId(String orgId) {
            this.orgId = Objects.requireNonNull(orgId);
            return this;
        }
        public GetAccessListApiKeyResult build() {
            final var _resultValue = new GetAccessListApiKeyResult();
            _resultValue.accessCount = accessCount;
            _resultValue.apiKeyId = apiKeyId;
            _resultValue.cidrBlock = cidrBlock;
            _resultValue.created = created;
            _resultValue.id = id;
            _resultValue.ipAddress = ipAddress;
            _resultValue.lastUsed = lastUsed;
            _resultValue.lastUsedAddress = lastUsedAddress;
            _resultValue.orgId = orgId;
            return _resultValue;
        }
    }
}
