// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.mongodbatlas.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetStreamConnectionDbRoleToExecute {
    /**
     * @return The name of the role to use. Can be a built in role or a custom role.
     * 
     */
    private String role;
    /**
     * @return Selected networking type. Either `PUBLIC`, `VPC` or `PRIVATE_LINK`. Defaults to `PUBLIC`.
     * 
     */
    private String type;

    private GetStreamConnectionDbRoleToExecute() {}
    /**
     * @return The name of the role to use. Can be a built in role or a custom role.
     * 
     */
    public String role() {
        return this.role;
    }
    /**
     * @return Selected networking type. Either `PUBLIC`, `VPC` or `PRIVATE_LINK`. Defaults to `PUBLIC`.
     * 
     */
    public String type() {
        return this.type;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetStreamConnectionDbRoleToExecute defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String role;
        private String type;
        public Builder() {}
        public Builder(GetStreamConnectionDbRoleToExecute defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.role = defaults.role;
    	      this.type = defaults.type;
        }

        @CustomType.Setter
        public Builder role(String role) {
            if (role == null) {
              throw new MissingRequiredPropertyException("GetStreamConnectionDbRoleToExecute", "role");
            }
            this.role = role;
            return this;
        }
        @CustomType.Setter
        public Builder type(String type) {
            if (type == null) {
              throw new MissingRequiredPropertyException("GetStreamConnectionDbRoleToExecute", "type");
            }
            this.type = type;
            return this;
        }
        public GetStreamConnectionDbRoleToExecute build() {
            final var _resultValue = new GetStreamConnectionDbRoleToExecute();
            _resultValue.role = role;
            _resultValue.type = type;
            return _resultValue;
        }
    }
}
