// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.mongodbatlas.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class StreamConnectionNetworkingAccess {
    /**
     * @return Selected networking type. Either `PUBLIC` or `VPC`. Defaults to `PUBLIC`.
     * 
     */
    private String type;

    private StreamConnectionNetworkingAccess() {}
    /**
     * @return Selected networking type. Either `PUBLIC` or `VPC`. Defaults to `PUBLIC`.
     * 
     */
    public String type() {
        return this.type;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(StreamConnectionNetworkingAccess defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String type;
        public Builder() {}
        public Builder(StreamConnectionNetworkingAccess defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.type = defaults.type;
        }

        @CustomType.Setter
        public Builder type(String type) {
            if (type == null) {
              throw new MissingRequiredPropertyException("StreamConnectionNetworkingAccess", "type");
            }
            this.type = type;
            return this;
        }
        public StreamConnectionNetworkingAccess build() {
            final var _resultValue = new StreamConnectionNetworkingAccess();
            _resultValue.type = type;
            return _resultValue;
        }
    }
}
