// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Mongodbatlas.Inputs
{

    public sealed class AdvancedClusterConnectionStringArgs : global::Pulumi.ResourceArgs
    {
        [Input("private")]
        public Input<string>? Private { get; set; }

        [Input("privateEndpoints")]
        private InputList<Inputs.AdvancedClusterConnectionStringPrivateEndpointArgs>? _privateEndpoints;
        public InputList<Inputs.AdvancedClusterConnectionStringPrivateEndpointArgs> PrivateEndpoints
        {
            get => _privateEndpoints ?? (_privateEndpoints = new InputList<Inputs.AdvancedClusterConnectionStringPrivateEndpointArgs>());
            set => _privateEndpoints = value;
        }

        [Input("privateSrv")]
        public Input<string>? PrivateSrv { get; set; }

        [Input("standard")]
        public Input<string>? Standard { get; set; }

        [Input("standardSrv")]
        public Input<string>? StandardSrv { get; set; }

        public AdvancedClusterConnectionStringArgs()
        {
        }
        public static new AdvancedClusterConnectionStringArgs Empty => new AdvancedClusterConnectionStringArgs();
    }
}
