// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Mongodbatlas.Inputs
{

    public sealed class AlertConfigurationMetricThresholdConfigArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Name of the metric to check. The full list being quite large, please refer to atlas docs [here for general metrics](https://docs.atlas.mongodb.com/reference/alert-host-metrics/#measurement-types) and [here for serverless metrics](https://www.mongodb.com/docs/atlas/reference/api/alert-configurations-create-config/#serverless-measurements)
        /// </summary>
        [Input("metricName", required: true)]
        public Input<string> MetricName { get; set; } = null!;

        /// <summary>
        /// This must be set to AVERAGE. Atlas computes the current metric value as an average.
        /// </summary>
        [Input("mode")]
        public Input<string>? Mode { get; set; }

        [Input("operator")]
        public Input<string>? Operator { get; set; }

        [Input("threshold")]
        public Input<double>? Threshold { get; set; }

        [Input("units")]
        public Input<string>? Units { get; set; }

        public AlertConfigurationMetricThresholdConfigArgs()
        {
        }
        public static new AlertConfigurationMetricThresholdConfigArgs Empty => new AlertConfigurationMetricThresholdConfigArgs();
    }
}
