// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Mongodbatlas.Inputs
{

    public sealed class CloudUserOrgAssignmentRolesGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("orgRoles")]
        private InputList<string>? _orgRoles;

        /// <summary>
        /// One or more organization level roles to assign the MongoDB Cloud user.
        /// </summary>
        public InputList<string> OrgRoles
        {
            get => _orgRoles ?? (_orgRoles = new InputList<string>());
            set => _orgRoles = value;
        }

        [Input("projectRoleAssignments")]
        private InputList<Inputs.CloudUserOrgAssignmentRolesProjectRoleAssignmentGetArgs>? _projectRoleAssignments;

        /// <summary>
        /// List of project level role assignments to assign the MongoDB Cloud user.
        /// </summary>
        public InputList<Inputs.CloudUserOrgAssignmentRolesProjectRoleAssignmentGetArgs> ProjectRoleAssignments
        {
            get => _projectRoleAssignments ?? (_projectRoleAssignments = new InputList<Inputs.CloudUserOrgAssignmentRolesProjectRoleAssignmentGetArgs>());
            set => _projectRoleAssignments = value;
        }

        public CloudUserOrgAssignmentRolesGetArgs()
        {
        }
        public static new CloudUserOrgAssignmentRolesGetArgs Empty => new CloudUserOrgAssignmentRolesGetArgs();
    }
}
