// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Mongodbatlas.Inputs
{

    public sealed class DataLakePipelineSnapshotArgs : global::Pulumi.ResourceArgs
    {
        [Input("copyRegion")]
        public Input<string>? CopyRegion { get; set; }

        [Input("createdAt")]
        public Input<string>? CreatedAt { get; set; }

        [Input("expiresAt")]
        public Input<string>? ExpiresAt { get; set; }

        [Input("frequencyYype")]
        public Input<string>? FrequencyYype { get; set; }

        /// <summary>
        /// Unique 24-hexadecimal digit string that identifies the Data Lake Pipeline.
        /// </summary>
        [Input("id")]
        public Input<string>? Id { get; set; }

        [Input("masterKey")]
        public Input<string>? MasterKey { get; set; }

        [Input("mongodVersion")]
        public Input<string>? MongodVersion { get; set; }

        [Input("policies")]
        private InputList<string>? _policies;
        public InputList<string> Policies
        {
            get => _policies ?? (_policies = new InputList<string>());
            set => _policies = value;
        }

        /// <summary>
        /// Target cloud provider for this Data Lake Pipeline.
        /// </summary>
        [Input("provider")]
        public Input<string>? Provider { get; set; }

        [Input("replicaSetName")]
        public Input<string>? ReplicaSetName { get; set; }

        [Input("size")]
        public Input<int>? Size { get; set; }

        [Input("snapshotType")]
        public Input<string>? SnapshotType { get; set; }

        [Input("status")]
        public Input<string>? Status { get; set; }

        /// <summary>
        /// Type of ingestion source of this Data Lake Pipeline.
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        public DataLakePipelineSnapshotArgs()
        {
        }
        public static new DataLakePipelineSnapshotArgs Empty => new DataLakePipelineSnapshotArgs();
    }
}
