// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * **WARNING:** The data source `mongodbatlas.CloudProviderAccess` is deprecated and will be removed in version v1.14.0, use the data source `mongodbatlas.CloudProviderAccessSetup` instead.
 *
 * `mongodbatlas.CloudProviderAccess` allows you to get the list of cloud provider access roles, currently only AWS and Azure is supported.
 *
 * > **NOTE:** Groups and projects are synonymous terms. You may find `groupId` in the official documentation.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as mongodbatlas from "@pulumi/mongodbatlas";
 *
 * const testRole = new mongodbatlas.CloudProviderAccess("testRole", {
 *     projectId: "64259ee860c43338194b0f8e",
 *     providerName: "AWS",
 * });
 * const all = mongodbatlas.getCloudProviderAccessOutput({
 *     projectId: testRole.projectId,
 * });
 * ```
 */
export function getCloudProviderAccess(args: GetCloudProviderAccessArgs, opts?: pulumi.InvokeOptions): Promise<GetCloudProviderAccessResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("mongodbatlas:index/getCloudProviderAccess:getCloudProviderAccess", {
        "projectId": args.projectId,
    }, opts);
}

/**
 * A collection of arguments for invoking getCloudProviderAccess.
 */
export interface GetCloudProviderAccessArgs {
    /**
     * The unique ID for the project to get all Cloud Provider Access
     */
    projectId: string;
}

/**
 * A collection of values returned by getCloudProviderAccess.
 */
export interface GetCloudProviderAccessResult {
    /**
     * A list where each represents a Cloud Provider Access Role.
     */
    readonly awsIamRoles: outputs.GetCloudProviderAccessAwsIamRole[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly projectId: string;
}
/**
 * **WARNING:** The data source `mongodbatlas.CloudProviderAccess` is deprecated and will be removed in version v1.14.0, use the data source `mongodbatlas.CloudProviderAccessSetup` instead.
 *
 * `mongodbatlas.CloudProviderAccess` allows you to get the list of cloud provider access roles, currently only AWS and Azure is supported.
 *
 * > **NOTE:** Groups and projects are synonymous terms. You may find `groupId` in the official documentation.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as mongodbatlas from "@pulumi/mongodbatlas";
 *
 * const testRole = new mongodbatlas.CloudProviderAccess("testRole", {
 *     projectId: "64259ee860c43338194b0f8e",
 *     providerName: "AWS",
 * });
 * const all = mongodbatlas.getCloudProviderAccessOutput({
 *     projectId: testRole.projectId,
 * });
 * ```
 */
export function getCloudProviderAccessOutput(args: GetCloudProviderAccessOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetCloudProviderAccessResult> {
    return pulumi.output(args).apply((a: any) => getCloudProviderAccess(a, opts))
}

/**
 * A collection of arguments for invoking getCloudProviderAccess.
 */
export interface GetCloudProviderAccessOutputArgs {
    /**
     * The unique ID for the project to get all Cloud Provider Access
     */
    projectId: pulumi.Input<string>;
}
