// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * `privatelinkEndpointsServiceServerless` Describes the list of all Serverless PrivateLink Endpoint Service resource.
 *
 * > **NOTE:** Groups and projects are synonymous terms. You may find groupId in the official documentation.
 */
export function getPrivatelinkEndpointsServiceServerless(args: GetPrivatelinkEndpointsServiceServerlessArgs, opts?: pulumi.InvokeOptions): Promise<GetPrivatelinkEndpointsServiceServerlessResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("mongodbatlas:index/getPrivatelinkEndpointsServiceServerless:getPrivatelinkEndpointsServiceServerless", {
        "instanceName": args.instanceName,
        "itemsPerPage": args.itemsPerPage,
        "pageNum": args.pageNum,
        "projectId": args.projectId,
    }, opts);
}

/**
 * A collection of arguments for invoking getPrivatelinkEndpointsServiceServerless.
 */
export interface GetPrivatelinkEndpointsServiceServerlessArgs {
    /**
     * Human-readable label that identifies the serverless instance
     */
    instanceName: string;
    itemsPerPage?: number;
    pageNum?: number;
    /**
     * Unique 24-digit hexadecimal string that identifies the project.
     */
    projectId: string;
}

/**
 * A collection of values returned by getPrivatelinkEndpointsServiceServerless.
 */
export interface GetPrivatelinkEndpointsServiceServerlessResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly instanceName: string;
    readonly itemsPerPage?: number;
    readonly pageNum?: number;
    readonly projectId: string;
    /**
     * Each element in the `result` array is one private serverless endpoint.
     */
    readonly results: outputs.GetPrivatelinkEndpointsServiceServerlessResult[];
}
/**
 * `privatelinkEndpointsServiceServerless` Describes the list of all Serverless PrivateLink Endpoint Service resource.
 *
 * > **NOTE:** Groups and projects are synonymous terms. You may find groupId in the official documentation.
 */
export function getPrivatelinkEndpointsServiceServerlessOutput(args: GetPrivatelinkEndpointsServiceServerlessOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetPrivatelinkEndpointsServiceServerlessResult> {
    return pulumi.output(args).apply((a: any) => getPrivatelinkEndpointsServiceServerless(a, opts))
}

/**
 * A collection of arguments for invoking getPrivatelinkEndpointsServiceServerless.
 */
export interface GetPrivatelinkEndpointsServiceServerlessOutputArgs {
    /**
     * Human-readable label that identifies the serverless instance
     */
    instanceName: pulumi.Input<string>;
    itemsPerPage?: pulumi.Input<number>;
    pageNum?: pulumi.Input<number>;
    /**
     * Unique 24-digit hexadecimal string that identifies the project.
     */
    projectId: pulumi.Input<string>;
}
