// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * `mongodbatlas.ProjectMcpConfig` provides a Project Remote MCP Configuration resource. The resource lets you create, update, delete, and import a Remote MCP configuration for the specified Project.
 *
 * > **IMPORTANT:** This resource does not manage ingress secrets. Use `mongodbatlas.ProjectMcpConfigSecret` to create one.
 *
 * ## Example Usage
 *
 * ### S
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as mongodbatlas from "@pulumi/mongodbatlas";
 *
 * const _this = new mongodbatlas.ProjectMcpConfig("this", {
 *     projectId: projectId,
 *     mcpConfigName: "example-mcp-config",
 *     roles: ["GROUP_READ_ONLY"],
 *     ipAccessLists: [{
 *         cidrBlock: "203.0.113.0/24",
 *     }],
 * });
 * export const mcpConfigId = _this.mcpConfigId;
 * export const clientId = _this.clientId;
 * export const egressClientId = _this.egressClientId;
 * ```
 *
 * ## Import
 *
 * Import the MCP Config resource by using the Project ID and MCP Config ID in the format `PROJECT_ID/MCP_CONFIG_ID`, e.g.
 * ```sh
 * $ pulumi import mongodbatlas:index/projectMcpConfig:ProjectMcpConfig test 6117ac2fe2a3d04ed27a987v/8423867e-394c-4f1e-9d81-32d323a1dd81
 * ```
 *
 * For more information, see [Create One MCP Configuration for One Project](https://www.mongodb.com/docs/api/doc/atlas-admin-api-v2/operation/operation-creategroupmcpconfig) in the MongoDB Atlas API documentation.
 */
export class ProjectMcpConfig extends pulumi.CustomResource {
    /**
     * Get an existing ProjectMcpConfig resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ProjectMcpConfigState, opts?: pulumi.CustomResourceOptions): ProjectMcpConfig {
        return new ProjectMcpConfig(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'mongodbatlas:index/projectMcpConfig:ProjectMcpConfig';

    /**
     * Returns true if the given object is an instance of ProjectMcpConfig.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ProjectMcpConfig {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ProjectMcpConfig.__pulumiType;
    }

    /**
     * Unique identifier for the Service Account client associated with this MCP configuration. Use this Service Account to connect to the Atlas Remote MCP.
     */
    declare public /*out*/ readonly clientId: pulumi.Output<string>;
    /**
     * Unique identifier for the egress Service Account client associated with this MCP configuration. This Service Account is managed by MongoDB Atlas.
     */
    declare public /*out*/ readonly egressClientId: pulumi.Output<string>;
    /**
     * List of IP access list entries that define allowed source addresses for this MCP configuration.
     */
    declare public readonly ipAccessLists: pulumi.Output<outputs.ProjectMcpConfigIpAccessList[]>;
    /**
     * Unique identifier that identifies this MCP configuration.
     */
    declare public /*out*/ readonly mcpConfigId: pulumi.Output<string>;
    /**
     * Human-readable name that identifies this MCP configuration.
     */
    declare public readonly mcpConfigName: pulumi.Output<string>;
    /**
     * Unique 24-hexadecimal digit string that identifies your project, also known as `groupId` in the official documentation.
     */
    declare public readonly projectId: pulumi.Output<string>;
    /**
     * List of project roles to assign to this MCP configuration.
     */
    declare public readonly roles: pulumi.Output<string[]>;

    /**
     * Create a ProjectMcpConfig resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ProjectMcpConfigArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ProjectMcpConfigArgs | ProjectMcpConfigState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ProjectMcpConfigState | undefined;
            resourceInputs["clientId"] = state?.clientId;
            resourceInputs["egressClientId"] = state?.egressClientId;
            resourceInputs["ipAccessLists"] = state?.ipAccessLists;
            resourceInputs["mcpConfigId"] = state?.mcpConfigId;
            resourceInputs["mcpConfigName"] = state?.mcpConfigName;
            resourceInputs["projectId"] = state?.projectId;
            resourceInputs["roles"] = state?.roles;
        } else {
            const args = argsOrState as ProjectMcpConfigArgs | undefined;
            if (args?.mcpConfigName === undefined && !opts.urn) {
                throw new Error("Missing required property 'mcpConfigName'");
            }
            if (args?.projectId === undefined && !opts.urn) {
                throw new Error("Missing required property 'projectId'");
            }
            if (args?.roles === undefined && !opts.urn) {
                throw new Error("Missing required property 'roles'");
            }
            resourceInputs["ipAccessLists"] = args?.ipAccessLists;
            resourceInputs["mcpConfigName"] = args?.mcpConfigName;
            resourceInputs["projectId"] = args?.projectId;
            resourceInputs["roles"] = args?.roles;
            resourceInputs["clientId"] = undefined /*out*/;
            resourceInputs["egressClientId"] = undefined /*out*/;
            resourceInputs["mcpConfigId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ProjectMcpConfig.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ProjectMcpConfig resources.
 */
export interface ProjectMcpConfigState {
    /**
     * Unique identifier for the Service Account client associated with this MCP configuration. Use this Service Account to connect to the Atlas Remote MCP.
     */
    clientId?: pulumi.Input<string | undefined>;
    /**
     * Unique identifier for the egress Service Account client associated with this MCP configuration. This Service Account is managed by MongoDB Atlas.
     */
    egressClientId?: pulumi.Input<string | undefined>;
    /**
     * List of IP access list entries that define allowed source addresses for this MCP configuration.
     */
    ipAccessLists?: pulumi.Input<pulumi.Input<inputs.ProjectMcpConfigIpAccessList>[] | undefined>;
    /**
     * Unique identifier that identifies this MCP configuration.
     */
    mcpConfigId?: pulumi.Input<string | undefined>;
    /**
     * Human-readable name that identifies this MCP configuration.
     */
    mcpConfigName?: pulumi.Input<string | undefined>;
    /**
     * Unique 24-hexadecimal digit string that identifies your project, also known as `groupId` in the official documentation.
     */
    projectId?: pulumi.Input<string | undefined>;
    /**
     * List of project roles to assign to this MCP configuration.
     */
    roles?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}

/**
 * The set of arguments for constructing a ProjectMcpConfig resource.
 */
export interface ProjectMcpConfigArgs {
    /**
     * List of IP access list entries that define allowed source addresses for this MCP configuration.
     */
    ipAccessLists?: pulumi.Input<pulumi.Input<inputs.ProjectMcpConfigIpAccessList>[] | undefined>;
    /**
     * Human-readable name that identifies this MCP configuration.
     */
    mcpConfigName: pulumi.Input<string>;
    /**
     * Unique 24-hexadecimal digit string that identifies your project, also known as `groupId` in the official documentation.
     */
    projectId: pulumi.Input<string>;
    /**
     * List of project roles to assign to this MCP configuration.
     */
    roles: pulumi.Input<pulumi.Input<string>[]>;
}
